import {pool} from '../../../../lib/db';import {cookies} from 'next/headers';export const dynamic='force-dynamic';
const e=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const money=v=>Number(v||0).toFixed(2);
export async function GET(req){const sid=(await cookies()).get('gastos_session')?.value;if(!sid)return new Response('No autorizado',{status:401});const sr=await pool.query('SELECT user_id FROM user_sessions WHERE id=$1 AND expires_at>NOW()',[sid]);if(!sr.rows[0])return new Response('No autorizado',{status:401});const uid=sr.rows[0].user_id,u=new URL(req.url),y=Number(u.searchParams.get('year')),m=Number(u.searchParams.get('month')),f=y+'-'+String(m).padStart(2,'0')+'-01',t=new Date(Date.UTC(y,m,1)).toISOString().slice(0,10),yf=y+'-01-01',yt=(y+1)+'-01-01';
const [i,x,cats,debts,months]=await Promise.all([
pool.query('SELECT occurred_on,concept,source,amount,status FROM income WHERE user_id=$3 AND deleted_at IS NULL AND occurred_on >= $1 AND occurred_on < $2 ORDER BY occurred_on',[f,t,uid]),
pool.query('SELECT occurred_on,concept,category,amount,status FROM expense WHERE user_id=$3 AND deleted_at IS NULL AND occurred_on >= $1 AND occurred_on < $2 ORDER BY occurred_on',[f,t,uid]),
pool.query("SELECT category,COALESCE(SUM(amount),0) total FROM expense WHERE user_id=$3 AND deleted_at IS NULL AND occurred_on >= $1 AND occurred_on < $2 GROUP BY category ORDER BY total DESC",[f,t,uid]),
pool.query("SELECT name,lender,original_amount,current_balance,installment_amount,total_installments,paid_installments,status FROM debts WHERE user_id=$1 ORDER BY status,name",[uid]),
pool.query("SELECT mm,COALESCE(SUM(inc),0) income,COALESCE(SUM(exp),0) expense FROM (SELECT EXTRACT(MONTH FROM occurred_on)::int mm,SUM(amount) inc,0::numeric exp FROM income WHERE user_id=$3 AND deleted_at IS NULL AND occurred_on >= $1 AND occurred_on < $2 GROUP BY 1 UNION ALL SELECT EXTRACT(MONTH FROM occurred_on)::int mm,0::numeric,SUM(amount) exp FROM expense WHERE user_id=$3 AND deleted_at IS NULL AND occurred_on >= $1 AND occurred_on < $2 GROUP BY 1) z GROUP BY mm ORDER BY mm",[yf,yt,uid])
]);const ti=i.rows.reduce((a,r)=>a+Number(r.amount),0),te=x.rows.reduce((a,r)=>a+Number(r.amount),0),bal=ti-te,paid=x.rows.filter(r=>r.status==='pagado').reduce((a,r)=>a+Number(r.amount),0),pending=x.rows.filter(r=>r.status!=='pagado').reduce((a,r)=>a+Number(r.amount),0);
const chart=(title,rows,max)=>'<h3>'+title+'</h3><table class="chart">'+rows.map(r=>'<tr><td>'+e(r.label)+'</td><td><div style="width:'+Math.max(2,Math.round(Number(r.value||0)/max*420))+'px"></div></td><td>'+money(r.value)+'</td></tr>').join('')+'</table>';
const catMax=Math.max(1,...cats.rows.map(r=>Number(r.total))),monthRows=months.rows.map(r=>({label:String(r.mm).padStart(2,'0')+'/'+y,value:Number(r.expense),income:Number(r.income)})),monthMax=Math.max(1,...monthRows.flatMap(r=>[r.value,r.income]));
let mov='<tr><th>Tipo</th><th>Fecha</th><th>Concepto</th><th>Categoría / Origen</th><th>Monto</th><th>Estado</th></tr>';for(const r of i.rows)mov+='<tr><td>Ingreso</td><td>'+e(String(r.occurred_on).slice(0,10))+'</td><td>'+e(r.concept)+'</td><td>'+e(r.source)+'</td><td>'+money(r.amount)+'</td><td>'+e(r.status)+'</td></tr>';for(const r of x.rows)mov+='<tr><td>Gasto</td><td>'+e(String(r.occurred_on).slice(0,10))+'</td><td>'+e(r.concept)+'</td><td>'+e(r.category)+'</td><td>'+money(r.amount)+'</td><td>'+e(r.status)+'</td></tr>';
let debt='<tr><th>Deuda</th><th>Entidad</th><th>Capital</th><th>Saldo</th><th>Cuota</th><th>Pagadas</th><th>Total cuotas</th><th>Estado</th></tr>'+debts.rows.map(r=>'<tr><td>'+e(r.name)+'</td><td>'+e(r.lender)+'</td><td>'+money(r.original_amount)+'</td><td>'+money(r.current_balance)+'</td><td>'+money(r.installment_amount)+'</td><td>'+e(r.paid_installments)+'</td><td>'+e(r.total_installments)+'</td><td>'+e(r.status)+'</td></tr>').join('');
let html='<!doctype html><html><head><meta charset="utf-8"><style>body{font-family:Arial;color:#172033}h1{margin-bottom:4px}.muted{color:#667085}table{border-collapse:collapse;width:100%;margin:12px 0 28px}th,td{border:1px solid #d9dee8;padding:7px;text-align:left}th{background:#eef2f7}.kpi td{font-size:16px;font-weight:bold}.chart td{border:0}.chart div{height:15px;background:#4b6bfb}.page{page-break-before:always}</style></head><body><h1>KNJ Finanzas · Informe '+String(m).padStart(2,'0')+'/'+y+'</h1><p class="muted">Resumen financiero exportado desde KNJ Finanzas</p><table class="kpi"><tr><th>Ingresos</th><th>Gastos</th><th>Balance</th><th>Gastos pagados</th><th>Pendientes</th></tr><tr><td>'+money(ti)+'</td><td>'+money(te)+'</td><td>'+money(bal)+'</td><td>'+money(paid)+'</td><td>'+money(pending)+'</td></tr></table>'+chart('Gastos por categoría',cats.rows.map(r=>({label:r.category,value:r.total})),catMax)+'<h3>Evolución anual</h3><table><tr><th>Mes</th><th>Ingresos</th><th>Gastos</th><th>Balance</th></tr>'+monthRows.map(r=>'<tr><td>'+r.label+'</td><td>'+money(r.income)+'</td><td>'+money(r.value)+'</td><td>'+money(r.income-r.value)+'</td></tr>').join('')+'</table><div class="page"><h2>Deudas y cuotas</h2><table>'+debt+'</table></div><div class="page"><h2>Detalle de movimientos</h2><table>'+mov+'</table></div></body></html>';
return new Response('\uFEFF'+html,{headers:{'Content-Type':'application/vnd.ms-excel; charset=utf-8','Content-Disposition':'attachment; filename="KNJ-Finanzas-'+y+'-'+String(m).padStart(2,'0')+'.xls"'}})}
