import {currentUser} from '../../lib/auth';
import {pool} from '../../lib/db';
import {redirect} from 'next/navigation';
import {createUser,toggleUser,deleteUser,resetUserPassword} from '../auth-actions';
export const dynamic='force-dynamic';
const fmt=d=>d?new Date(d).toLocaleString('es-UY'):'Nunca';
export default async function Admin({searchParams}){
 const me=await currentUser();if(!me)redirect('/login');if(me.role!=='admin')redirect('/');
 const sp=await searchParams,q=String(sp?.q||'').trim().toLowerCase(),status=String(sp?.status||'all');
 const [users,logs,stats]=await Promise.all([
  pool.query('SELECT id,email,whatsapp,role,active,created_at,last_login_at FROM app_users ORDER BY role,email'),
  pool.query('SELECT a.*,u.email FROM audit_log a LEFT JOIN app_users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 100'),
  pool.query("SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE active)::int active,COUNT(*) FILTER(WHERE NOT active)::int inactive,COUNT(*) FILTER(WHERE created_at>=NOW()-INTERVAL '30 days')::int recent FROM app_users")
 ]);
 const s=stats.rows[0],filtered=users.rows.filter(u=>(!q||u.email.toLowerCase().includes(q)||String(u.whatsapp||'').toLowerCase().includes(q))&&(status==='all'||(status==='active'&&u.active)||(status==='inactive'&&!u.active)||(status==='admin'&&u.role==='admin')));
 return <main className="wrap admin-page">
  <header className="admin-head"><div><span className="eyebrow">KNJ · ADMINISTRACIÓN</span><h1>Centro de control</h1><p className="muted">Gestiona usuarios, accesos y actividad desde un solo lugar.</p></div><div className="admin-top-actions"><a className="export-btn" href="/">← Panel financiero</a><a className="export-btn" href="/api/export/backup">Backup</a></div></header>
  <section className="admin-kpis"><div className="card"><small>Usuarios</small><strong>{s.total}</strong><span>Total registrado</span></div><div className="card"><small>Activos</small><strong className="positive">{s.active}</strong><span>Con acceso</span></div><div className="card"><small>Desactivados</small><strong className="negative">{s.inactive}</strong><span>Sin acceso</span></div><div className="card"><small>Nuevos 30 días</small><strong>{s.recent}</strong><span>Altas recientes</span></div></section>
  <section className="admin-layout">
   <aside className="card admin-create"><span className="eyebrow">ALTA MANUAL</span><h2>Crear usuario</h2><p className="muted">Crea una cuenta directamente desde administración.</p><form action={createUser} className="stack"><label><span>Email</span><input name="email" type="email" placeholder="usuario@email.com" required/></label><label><span>WhatsApp</span><input name="whatsapp" type="tel" placeholder="+598..." required/></label><label><span>Contraseña inicial</span><input name="password" type="password" minLength="8" placeholder="Mínimo 8 caracteres" required/></label><button>Crear cuenta</button></form><div className="admin-note"><b>Acceso</b><span>El usuario podrá entrar inmediatamente después de crear la cuenta.</span></div></aside>
   <div className="card admin-users"><div className="admin-section-head"><div><span className="eyebrow">CUENTAS</span><h2>Usuarios</h2></div><b>{filtered.length} mostrados</b></div>
    <form className="admin-filters"><input name="q" defaultValue={q} placeholder="Buscar email o WhatsApp"/><select name="status" defaultValue={status}><option value="all">Todos</option><option value="active">Activos</option><option value="inactive">Desactivados</option><option value="admin">Administradores</option></select><button>Filtrar</button>{(q||status!=='all')&&<a className="export-btn" href="/admin">Limpiar</a>}</form>
    <div className="admin-user-list">{filtered.length===0?<p className="empty">No hay usuarios con estos filtros.</p>:filtered.map(u=><article className="admin-user" key={u.id}><div className="admin-user-main"><div className="admin-avatar">{u.email.slice(0,1).toUpperCase()}</div><div><b>{u.email}</b><span>{u.whatsapp||'Sin WhatsApp'}</span><small>ID #{u.id} · Alta {fmt(u.created_at)}</small></div></div><div className="admin-user-meta"><span className={'admin-status '+(u.active?'is-active':'is-inactive')}>{u.active?'Activa':'Desactivada'}</span><span className="role-chip">{u.role==='admin'?'Administrador':'Usuario'}</span><small>Último acceso: {fmt(u.last_login_at)}</small></div><div className="admin-user-actions">{u.id===me.id?<span className="muted">Tu cuenta</span>:u.role==='admin'?<span className="muted">Admin protegido</span>:<><details className="admin-reset"><summary>Contraseña</summary><form action={resetUserPassword}><input type="hidden" name="id" value={u.id}/><input name="new_password" type="password" minLength="8" placeholder="Nueva contraseña" required/><button>Restablecer</button></form></details><form action={toggleUser}><input type="hidden" name="id" value={u.id}/><button className="secondary-btn">{u.active?'Desactivar':'Activar'}</button></form><form action={deleteUser}><input type="hidden" name="id" value={u.id}/><button className="delete-btn">Eliminar</button></form></>}</div></article>)}</div>
   </div>
  </section>
  <section className="card audit-card"><div className="admin-section-head"><div><span className="eyebrow">SEGURIDAD</span><h2>Actividad reciente</h2></div><span className="muted">Últimos 100 eventos</span></div><div className="audit-list">{logs.rows.map(l=><div className="audit-row" key={l.id}><span>{fmt(l.created_at)}</span><b>{l.email||'Sistema'}</b><span>{l.action}</span><small>{l.entity||''}{l.entity_id?' #'+l.entity_id:''}</small></div>)}</div></section>
 </main>
}