'use server';
import {pool} from '../lib/db';
import {revalidatePath} from 'next/cache';
import {requireUser,audit} from '../lib/auth';
const done=()=>revalidatePath('/'),s=v=>String(v??'').trim(),n=v=>{const x=Number(v);if(!Number.isFinite(x))throw new Error('Valor numérico inválido');return x};
const required=(v,l)=>{const x=s(v);if(!x)throw new Error(l+' es obligatorio');return x};
const validDate=(v,{optional=false}={})=>{const x=s(v);if(!x&&optional)return null;if(!/^\d{4}-\d{2}-\d{2}$/.test(x))throw new Error('Fecha inválida');const d=new Date(x+'T00:00:00Z');if(Number.isNaN(d.getTime())||d.toISOString().slice(0,10)!==x)throw new Error('Fecha inválida');return x};
const status=v=>{const x=s(v);if(!['pagado','pendiente'].includes(x))throw new Error('Estado inválido');return x};
const positive=(v,l='Monto')=>{const x=n(v);if(x<=0)throw new Error(l+' debe ser mayor a 0');return x},nonNegative=(v,l='Monto')=>{const x=n(v);if(x<0)throw new Error(l+' no puede ser negativo');return x};
async function owner(table,id,u){const r=await pool.query('SELECT id FROM '+table+' WHERE id=$1 AND user_id=$2',[n(id),u.id]);if(!r.rows[0])throw new Error('Registro no encontrado');return n(id)}
export async function addIncome(fd){const u=await requireUser(),r=await pool.query('INSERT INTO income(concept,source,amount,occurred_on,status,account_id,user_id) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id',[required(fd.get('concept'),'Concepto'),s(fd.get('source'))||'extra',positive(fd.get('amount')),validDate(fd.get('occurred_on')),status(fd.get('status')||'pagado'),fd.get('account_id')?await owner('accounts',fd.get('account_id'),u):null,u.id]);await audit(u.id,'create','income',r.rows[0].id);done()}
export async function addExpense(fd){const u=await requireUser(),r=await pool.query('INSERT INTO expense(concept,category,amount,occurred_on,status,user_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING id',[required(fd.get('concept'),'Concepto'),s(fd.get('category')),positive(fd.get('amount')),validDate(fd.get('occurred_on')),status(fd.get('status')||'pagado'),u.id]);await audit(u.id,'create','expense',r.rows[0].id);done()}
export async function updateIncome(fd){const u=await requireUser(),id=await owner('income',fd.get('id'),u),account=fd.get('account_id')?await owner('accounts',fd.get('account_id'),u):null;await pool.query('UPDATE income SET concept=$1,source=$2,amount=$3,occurred_on=$4,status=$5,account_id=$6 WHERE id=$7 AND user_id=$8',[required(fd.get('concept'),'Concepto'),s(fd.get('source')),positive(fd.get('amount')),validDate(fd.get('occurred_on')),status(fd.get('status')),account,id,u.id]);await audit(u.id,'update','income',id);done()}
export async function updateExpense(fd){const u=await requireUser(),id=await owner('expense',fd.get('id'),u),dest=s(fd.get('destination')),parts=dest.split(':'),account=parts[0]==='account'&&parts[1]?await owner('accounts',parts[1],u):null,card=parts[0]==='card'&&parts[1]?await owner('credit_cards',parts[1],u):null;await pool.query('UPDATE expense SET concept=$1,category=$2,amount=$3,occurred_on=$4,status=$5,account_id=$6,credit_card_id=$7 WHERE id=$8 AND user_id=$9',[required(fd.get('concept'),'Concepto'),s(fd.get('category')),positive(fd.get('amount')),validDate(fd.get('occurred_on')),status(fd.get('status')),account,card,id,u.id]);await audit(u.id,'update','expense',id);done()}
export async function deleteIncome(fd){const u=await requireUser(),id=await owner('income',fd.get('id'),u);await pool.query('UPDATE income SET deleted_at=NOW() WHERE id=$1 AND user_id=$2',[id,u.id]);await audit(u.id,'delete','income',id);done()}
export async function deleteExpense(fd){const u=await requireUser(),id=await owner('expense',fd.get('id'),u);await pool.query('UPDATE expense SET deleted_at=NOW() WHERE id=$1 AND user_id=$2',[id,u.id]);await audit(u.id,'delete','expense',id);done()}
export async function restoreMovement(kind,id){const u=await requireUser(),table=kind==='income'?'income':'expense',mid=await owner(table,id,u);await pool.query('UPDATE '+table+' SET deleted_at=NULL WHERE id=$1 AND user_id=$2',[mid,u.id]);await audit(u.id,'restore',table,mid);done()}
export async function duplicateMovement(kind,id){const u=await requireUser(),table=kind==='income'?'income':'expense',mid=await owner(table,id,u);let r;if(kind==='income')r=await pool.query('INSERT INTO income(concept,source,amount,occurred_on,status,account_id,user_id) SELECT concept,source,amount,occurred_on,status,account_id,$2 FROM income WHERE id=$1 AND user_id=$2 RETURNING id',[mid,u.id]);else r=await pool.query('INSERT INTO expense(concept,category,amount,occurred_on,status,account_id,credit_card_id,user_id) SELECT concept,category,amount,occurred_on,status,account_id,credit_card_id,$2 FROM expense WHERE id=$1 AND user_id=$2 RETURNING id',[mid,u.id]);await audit(u.id,'duplicate',table,r.rows[0]?.id,{source_id:mid});done()}
export async function setBudget(fd){const u=await requireUser(),cid=await owner('categories',fd.get('category_id'),u);await pool.query('INSERT INTO budgets(category_id,year,month,amount,user_id) VALUES($1,$2,$3,$4,$5) ON CONFLICT(category_id,year,month) DO UPDATE SET amount=EXCLUDED.amount,user_id=EXCLUDED.user_id',[cid,n(fd.get('view_year')),n(fd.get('view_month')),nonNegative(fd.get('amount'),'Presupuesto'),u.id]);await audit(u.id,'set_budget','budget',null);done()}
export async function setMonthlyBudget(fd){const u=await requireUser();await pool.query('INSERT INTO monthly_budgets(year,month,amount,user_id) VALUES($1,$2,$3,$4) ON CONFLICT(user_id,year,month) DO UPDATE SET amount=EXCLUDED.amount',[n(fd.get('view_year')),n(fd.get('view_month')),nonNegative(fd.get('amount'),'Presupuesto'),u.id]);await audit(u.id,'set_monthly_budget','monthly_budget');done()}
export async function addCategory(fd){const u=await requireUser(),name=required(fd.get('name'),'Categoría');const r=await pool.query('INSERT INTO categories(name,sort_order,user_id) VALUES($1,(SELECT COALESCE(MAX(sort_order),0)+1 FROM categories WHERE user_id=$2),$2) ON CONFLICT(user_id,name) DO UPDATE SET active=true RETURNING id',[name,u.id]);await audit(u.id,'create','category',r.rows[0].id);done()}
export async function toggleCategory(fd){const u=await requireUser(),id=await owner('categories',fd.get('id'),u);await pool.query('UPDATE categories SET active=NOT active WHERE id=$1 AND user_id=$2',[id,u.id]);await audit(u.id,'toggle','category',id);done()}
export async function addRecurring(fd){const u=await requireUser(),r=await pool.query('INSERT INTO recurring_items(kind,concept,category,source,amount,day_of_month,status,start_date,end_date,user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id',[s(fd.get('kind')),required(fd.get('concept'),'Concepto'),s(fd.get('category'))||null,s(fd.get('source'))||null,positive(fd.get('amount')),Math.min(28,Math.max(1,n(fd.get('day_of_month'))||1)),status(fd.get('status')||'pendiente'),validDate(fd.get('start_date'),{optional:true}),validDate(fd.get('end_date'),{optional:true}),u.id]);await audit(u.id,'create','recurring',r.rows[0].id);done()}
export async function updateRecurring(fd){const u=await requireUser(),id=await owner('recurring_items',fd.get('id'),u);await pool.query('UPDATE recurring_items SET concept=$1,amount=$2,day_of_month=$3,status=$4,start_date=$5,end_date=$6 WHERE id=$7 AND user_id=$8',[required(fd.get('concept'),'Concepto'),positive(fd.get('amount')),n(fd.get('day_of_month')),status(fd.get('status')),validDate(fd.get('start_date'),{optional:true}),validDate(fd.get('end_date'),{optional:true}),id,u.id]);await audit(u.id,'update','recurring',id);done()}
export async function toggleRecurring(fd){const u=await requireUser(),id=await owner('recurring_items',fd.get('id'),u);await pool.query('UPDATE recurring_items SET active=NOT active WHERE id=$1 AND user_id=$2',[id,u.id]);await audit(u.id,'toggle','recurring',id);done()}
export async function deleteRecurring(fd){const u=await requireUser(),id=await owner('recurring_items',fd.get('id'),u);await pool.query('DELETE FROM recurring_items WHERE id=$1 AND user_id=$2',[id,u.id]);await audit(u.id,'delete','recurring',id);done()}
export async function addGoal(fd){const u=await requireUser(),r=await pool.query('INSERT INTO savings_goals(name,target_amount,current_amount,target_date,user_id) VALUES($1,$2,$3,$4,$5) RETURNING id',[required(fd.get('name'),'Meta'),positive(fd.get('target_amount'),'Objetivo'),nonNegative(fd.get('current_amount'),'Ahorrado'),validDate(fd.get('target_date'),{optional:true}),u.id]);await audit(u.id,'create','goal',r.rows[0].id);done()}
export async function updateGoal(fd){const u=await requireUser(),id=await owner('savings_goals',fd.get('id'),u);await pool.query('UPDATE savings_goals SET current_amount=$1,target_amount=$2,target_date=$3 WHERE id=$4 AND user_id=$5',[nonNegative(fd.get('current_amount'),'Ahorrado'),positive(fd.get('target_amount'),'Objetivo'),validDate(fd.get('target_date'),{optional:true}),id,u.id]);await audit(u.id,'update','goal',id);done()}
export async function deleteGoal(fd){const u=await requireUser(),id=await owner('savings_goals',fd.get('id'),u);await pool.query('DELETE FROM savings_goals WHERE id=$1 AND user_id=$2',[id,u.id]);await audit(u.id,'delete','goal',id);done()}
export async function importCsv(fd){const u=await requireUser(),raw=s(fd.get('csv'));if(!raw)return;const lines=raw.split(/\r?\n/).filter(Boolean),header=lines.shift()?.toLowerCase().split(',').map(x=>x.trim())||[],client=await pool.connect();let count=0;try{await client.query('BEGIN');for(const line of lines){const v=line.split(',').map(x=>x.trim().replace(/^"|"$/g,'')),row=Object.fromEntries(header.map((h,i)=>[h,v[i]||'']));if(row.tipo==='ingreso'){await client.query('INSERT INTO income(concept,source,amount,occurred_on,status,user_id) VALUES($1,$2,$3,$4,$5,$6)',[row.concepto,row.origen||'extra',positive(row.monto),validDate(row.fecha),status(row.estado||'pagado'),u.id]);count++}if(row.tipo==='gasto'){await client.query('INSERT INTO expense(concept,category,amount,occurred_on,status,user_id) VALUES($1,$2,$3,$4,$5,$6)',[row.concepto,row.categoria||'Otros',positive(row.monto),validDate(row.fecha),status(row.estado||'pagado'),u.id]);count++}}await client.query('COMMIT')}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}await audit(u.id,'import_csv','movement',null,{count});done()}
export async function addAccount(fd){const u=await requireUser(),r=await pool.query('INSERT INTO accounts(name,kind,opening_balance,user_id) VALUES($1,$2,$3,$4) RETURNING id',[required(fd.get('name'),'Cuenta'),s(fd.get('kind'))||'bank',n(fd.get('opening_balance')||0),u.id]);await audit(u.id,'create','account',r.rows[0].id);done()}
export async function addCard(fd){const u=await requireUser(),account=fd.get('account_id')?await owner('accounts',fd.get('account_id'),u):null,r=await pool.query('INSERT INTO credit_cards(name,closing_day,due_day,account_id,user_id) VALUES($1,$2,$3,$4,$5) RETURNING id',[required(fd.get('name'),'Tarjeta'),n(fd.get('closing_day')),n(fd.get('due_day')),account,u.id]);await audit(u.id,'create','card',r.rows[0].id);done()}
export async function addTransfer(fd){const u=await requireUser(),a=await owner('accounts',fd.get('from_account_id'),u),b=await owner('accounts',fd.get('to_account_id'),u);if(a===b)throw new Error('Las cuentas deben ser diferentes');const r=await pool.query('INSERT INTO transfers(from_account_id,to_account_id,amount,occurred_on,notes,user_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING id',[a,b,positive(fd.get('amount')),validDate(fd.get('occurred_on')),s(fd.get('notes'))||null,u.id]);await audit(u.id,'create','transfer',r.rows[0].id);done()}
export async function addDebt(fd){const u=await requireUser(),amount=positive(fd.get('original_amount'),'Deuda'),installment=fd.get('installment_amount')?positive(fd.get('installment_amount'),'Cuota'):null,first=validDate(fd.get('due_date'),{optional:true}),total=fd.get('total_installments')?Math.max(1,n(fd.get('total_installments'))):null,client=await pool.connect();let id;try{await client.query('BEGIN');const r=await client.query('INSERT INTO debts(name,lender,original_amount,current_balance,installment_amount,due_date,first_due_date,total_installments,user_id) VALUES($1,$2,$3,$3,$4,$5,$5,$6,$7) RETURNING id',[required(fd.get('name'),'Deuda'),s(fd.get('lender'))||null,amount,installment,first,total,u.id]);id=r.rows[0].id;if(installment&&first&&total){let remaining=Math.round(amount*100);for(let k=0;k<total;k++){const d=new Date(first+'T00:00:00Z');d.setUTCMonth(d.getUTCMonth()+k);const cents=k===total-1?remaining:Math.min(remaining,Math.round(installment*100));if(cents<=0)break;await client.query('INSERT INTO debt_installments(debt_id,installment_number,due_date,amount) VALUES($1,$2,$3,$4)',[id,k+1,d.toISOString().slice(0,10),cents/100]);remaining-=cents}}await client.query('COMMIT')}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}await audit(u.id,'create','debt',id);done()}
export async function addDebtInstallment(fd){const u=await requireUser(),id=await owner('debts',fd.get('debt_id'),u),amount=positive(fd.get('amount'),'Cuota'),due=validDate(fd.get('due_date')),r=await pool.query('INSERT INTO debt_installments(debt_id,installment_number,due_date,amount) SELECT $1,COALESCE(MAX(installment_number),0)+1,$2,$3 FROM debt_installments WHERE debt_id=$1 RETURNING id',[id,due,amount]);await pool.query('UPDATE debts SET due_date=LEAST(COALESCE(due_date,$1),$1) WHERE id=$2 AND user_id=$3',[due,id,u.id]);await audit(u.id,'create','debt_installment',r.rows[0].id,{debt_id:id});done()}
export async function payDebt(fd){const u=await requireUser(),id=await owner('debts',fd.get('debt_id'),u),amount=positive(fd.get('amount')),paidOn=validDate(fd.get('paid_on')),account=fd.get('account_id')?await owner('accounts',fd.get('account_id'),u):null,installmentId=fd.get('installment_id')?n(fd.get('installment_id')):null,client=await pool.connect();let expenseId;try{await client.query('BEGIN');const r=await client.query('SELECT current_balance,name FROM debts WHERE id=$1 AND user_id=$2 FOR UPDATE',[id,u.id]);if(!r.rows[0])throw new Error('Deuda inválida');if(installmentId){const ir=await client.query("SELECT id FROM debt_installments WHERE id=$1 AND debt_id=$2 AND status='pending' FOR UPDATE",[installmentId,id]);if(!ir.rows[0])throw new Error('Cuota inválida o ya pagada')}const applied=Math.min(amount,Number(r.rows[0].current_balance));await client.query("INSERT INTO categories(name,sort_order,user_id) VALUES('Préstamos',(SELECT COALESCE(MAX(sort_order),0)+1 FROM categories WHERE user_id=$1),$1) ON CONFLICT(user_id,name) DO UPDATE SET active=true",[u.id]);const er=await client.query("INSERT INTO expense(concept,category,amount,occurred_on,status,account_id,user_id) VALUES($1,'Préstamos',$2,$3,'pagado',$4,$5) RETURNING id",['Pago deuda: '+r.rows[0].name,applied,paidOn,account,u.id]);expenseId=er.rows[0].id;const pr=await client.query('INSERT INTO debt_payments(debt_id,amount,paid_on,expense_id,account_id) VALUES($1,$2,$3,$4,$5) RETURNING id',[id,applied,paidOn,expenseId,account]);if(installmentId)await client.query("UPDATE debt_installments SET status='paid',paid_on=$1,debt_payment_id=$2 WHERE id=$3",[paidOn,pr.rows[0].id,installmentId]);await client.query("UPDATE debts SET current_balance=GREATEST(0,current_balance-$1),paid_installments=paid_installments+CASE WHEN $4::bigint IS NULL THEN 0 ELSE 1 END,status=CASE WHEN current_balance-$1<=0 THEN 'paid' ELSE 'active' END WHERE id=$2 AND user_id=$3",[applied,id,u.id,installmentId]);await client.query('COMMIT')}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}await audit(u.id,'pay','debt',id,{expense_id:expenseId,installment_id:installmentId});done()}
export async function addTag(fd){const u=await requireUser(),name=required(fd.get('name'),'Etiqueta'),r=await pool.query('INSERT INTO tags(name,user_id) VALUES($1,$2) ON CONFLICT(user_id,name) DO UPDATE SET name=EXCLUDED.name RETURNING id',[name,u.id]);await audit(u.id,'create','tag',r.rows[0].id);done()}
export async function closeMonth(fd){const u=await requireUser(),y=n(fd.get('view_year')),m=n(fd.get('view_month')),from=y+'-'+String(m).padStart(2,'0')+'-01',to=new Date(Date.UTC(y,m,1)).toISOString().slice(0,10),[i,e]=await Promise.all([pool.query('SELECT COALESCE(SUM(amount),0) t FROM income WHERE user_id=$1 AND deleted_at IS NULL AND occurred_on >= $2 AND occurred_on < $3',[u.id,from,to]),pool.query('SELECT COALESCE(SUM(amount),0) t FROM expense WHERE user_id=$1 AND deleted_at IS NULL AND occurred_on >= $2 AND occurred_on < $3',[u.id,from,to])]),income=Number(i.rows[0].t),expense=Number(e.rows[0].t);await pool.query('INSERT INTO monthly_closures(year,month,income,expense,balance,snapshot,user_id) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7) ON CONFLICT(user_id,year,month) DO UPDATE SET income=EXCLUDED.income,expense=EXCLUDED.expense,balance=EXCLUDED.balance,snapshot=EXCLUDED.snapshot,closed_at=NOW()',[y,m,income,expense,income-expense,JSON.stringify({income,expense,balance:income-expense}),u.id]);await audit(u.id,'close_month','monthly_closure',null,{year:y,month:m});done()}
export async function addExpenseAdvanced(fd){const u=await requireUser(),concept=required(fd.get('concept'),'Concepto'),category=required(fd.get('category'),'Categoría'),amount=positive(fd.get('amount')),occurred=validDate(fd.get('occurred_on')),st=status(fd.get('status')||'pagado'),account=fd.get('account_id')?await owner('accounts',fd.get('account_id'),u):null,card=fd.get('credit_card_id')?await owner('credit_cards',fd.get('credit_card_id'),u):null,total=Math.max(1,Math.min(60,n(fd.get('installments')||1))),tags=s(fd.get('tags')).split(',').map(x=>x.trim()).filter(Boolean),client=await pool.connect(),ids=[];try{await client.query('BEGIN');const group=total>1?(await client.query('SELECT gen_random_uuid() id')).rows[0].id:null,totalCents=Math.round(amount*100),base=Math.floor(totalCents/total);for(let k=0;k<total;k++){const d=new Date(occurred+'T00:00:00Z');d.setUTCMonth(d.getUTCMonth()+k);const dt=d.toISOString().slice(0,10),part=(base+(k===total-1?totalCents-base*total:0))/100,r=await client.query('INSERT INTO expense(concept,category,amount,occurred_on,status,account_id,credit_card_id,installment_group,installment_number,installment_total,user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id',[total>1?concept+' ('+(k+1)+'/'+total+')':concept,category,part,dt,st,account,card,group,total>1?k+1:null,total>1?total:null,u.id]);ids.push(r.rows[0].id);for(const tag of tags){const tr=await client.query('INSERT INTO tags(name,user_id) VALUES($1,$2) ON CONFLICT(user_id,name) DO UPDATE SET name=EXCLUDED.name RETURNING id',[tag,u.id]);await client.query("INSERT INTO movement_tags(movement_kind,movement_id,tag_id) VALUES('expense',$1,$2) ON CONFLICT DO NOTHING",[r.rows[0].id,tr.rows[0].id])}}await client.query('COMMIT')}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}await audit(u.id,'create_installments','expense',ids[0]||null,{count:ids.length});done()}
export async function addReceipt(fd){const u=await requireUser(),file=fd.get('receipt');if(!file||typeof file.arrayBuffer!=='function'||!file.size)throw new Error('Comprobante es obligatorio');if(file.size>5*1024*1024)throw new Error('El comprobante supera 5 MB');const kind=s(fd.get('movement_kind')),id=n(fd.get('movement_id'));if(!['income','expense'].includes(kind))throw new Error('Movimiento inválido');await owner(kind,id,u);const r=await pool.query('INSERT INTO receipts(movement_kind,movement_id,file_name,mime_type,data,user_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING id',[kind,id,s(file.name)||'comprobante',s(file.type)||'application/octet-stream',Buffer.from(await file.arrayBuffer()),u.id]);await audit(u.id,'attach_receipt','receipt',r.rows[0].id,{movement_kind:kind,movement_id:id});done()}
