'use server';
import { pool } from '../lib/db';
import { revalidatePath } from 'next/cache';
const done=()=>revalidatePath('/'),s=v=>String(v??'').trim();
const n=v=>{const x=Number(v);if(!Number.isFinite(x))throw new Error('Monto o valor numérico inválido');return x};
const required=(v,label)=>{const x=s(v);if(!x)throw new Error(`${label} es obligatorio`);return x};
const validDate=(v,{optional=false}={})=>{const x=s(v);if(!x&&optional)return null;if(!/^\d{4}-\d{2}-\d{2}$/.test(x)||Number.isNaN(Date.parse(x+'T00:00:00Z')))throw new Error('Fecha inválida');return x};
const status=v=>{const x=s(v);if(!['pagado','pendiente'].includes(x))throw new Error('Estado inválido');return x};
const positive=(v,label='Monto')=>{const x=n(v);if(x<=0)throw new Error(`${label} debe ser mayor a 0`);return x};
const nonNegative=(v,label='Monto')=>{const x=n(v);if(x<0)throw new Error(`${label} no puede ser negativo`);return x};
export async function addIncome(fd){await pool.query('INSERT INTO income(concept,source,amount,occurred_on,status) VALUES($1,$2,$3,$4,$5)',[required(fd.get('concept'),'Concepto'),s(fd.get('source'))||'extra',positive(fd.get('amount')),validDate(fd.get('occurred_on')),status(fd.get('status')||'pagado')]);done()}
export async function addExpense(fd){await pool.query('INSERT INTO expense(concept,category,amount,occurred_on,status) VALUES($1,$2,$3,$4,$5)',[required(fd.get('concept'),'Concepto'),s(fd.get('category')),positive(fd.get('amount')),validDate(fd.get('occurred_on')),status(fd.get('status')||'pagado')]);done()}
export async function updateIncome(fd){await pool.query('UPDATE income SET concept=$1,source=$2,amount=$3,occurred_on=$4,status=$5 WHERE id=$6',[required(fd.get('concept'),'Concepto'),s(fd.get('source')),positive(fd.get('amount')),validDate(fd.get('occurred_on')),status(fd.get('status')),n(fd.get('id'))]);done()}
export async function updateExpense(fd){await pool.query('UPDATE expense SET concept=$1,category=$2,amount=$3,occurred_on=$4,status=$5 WHERE id=$6',[required(fd.get('concept'),'Concepto'),s(fd.get('category')),positive(fd.get('amount')),validDate(fd.get('occurred_on')),status(fd.get('status')),n(fd.get('id'))]);done()}
export async function deleteIncome(fd){await pool.query('UPDATE income SET deleted_at=NOW() WHERE id=$1',[n(fd.get('id'))]);done()}
export async function deleteExpense(fd){await pool.query('UPDATE expense SET deleted_at=NOW() WHERE id=$1',[n(fd.get('id'))]);done()}
export async function restoreMovement(kind,id){const table=kind==='income'?'income':'expense';await pool.query(`UPDATE ${table} SET deleted_at=NULL WHERE id=$1`,[n(id)]);done()}
export async function duplicateMovement(kind,id){if(kind==='income')await pool.query(`INSERT INTO income(concept,source,amount,occurred_on,status) SELECT concept,source,amount,occurred_on,status FROM income WHERE id=$1`,[n(id)]);else await pool.query(`INSERT INTO expense(concept,category,amount,occurred_on,status) SELECT concept,category,amount,occurred_on,status FROM expense WHERE id=$1`,[n(id)]);done()}
export async function setBudget(fd){await pool.query(`INSERT INTO budgets(category_id,year,month,amount) VALUES($1,$2,$3,$4) ON CONFLICT(category_id,year,month) DO UPDATE SET amount=EXCLUDED.amount`,[n(fd.get('category_id')),n(fd.get('view_year')),n(fd.get('view_month')),nonNegative(fd.get('amount'),'Presupuesto')]);done()}
export async function setMonthlyBudget(fd){await pool.query(`INSERT INTO monthly_budgets(year,month,amount) VALUES($1,$2,$3) ON CONFLICT(year,month) DO UPDATE SET amount=EXCLUDED.amount`,[n(fd.get('view_year')),n(fd.get('view_month')),nonNegative(fd.get('amount'),'Presupuesto')]);done()}
export async function addCategory(fd){await pool.query('INSERT INTO categories(name,sort_order) VALUES($1,(SELECT COALESCE(MAX(sort_order),0)+1 FROM categories)) ON CONFLICT(name) DO UPDATE SET active=true',[required(fd.get('name'),'Categoría')]);done()}
export async function toggleCategory(fd){await pool.query('UPDATE categories SET active=NOT active WHERE id=$1',[n(fd.get('id'))]);done()}
export async function addRecurring(fd){await pool.query('INSERT INTO recurring_items(kind,concept,category,source,amount,day_of_month,status,start_date,end_date) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[s(fd.get('kind')),required(fd.get('concept'),'Concepto'),s(fd.get('category'))||null,s(fd.get('source'))||null,positive(fd.get('amount')),Math.min(28,Math.max(1,n(fd.get('day_of_month'))||1)),status(fd.get('status')||'pendiente'),validDate(fd.get('start_date'),{optional:true}),validDate(fd.get('end_date'),{optional:true})]);done()}
export async function updateRecurring(fd){await pool.query('UPDATE recurring_items SET concept=$1,amount=$2,day_of_month=$3,status=$4,start_date=$5,end_date=$6 WHERE id=$7',[required(fd.get('concept'),'Concepto'),positive(fd.get('amount')),n(fd.get('day_of_month')),status(fd.get('status')),validDate(fd.get('start_date'),{optional:true}),validDate(fd.get('end_date'),{optional:true}),n(fd.get('id'))]);done()}
export async function toggleRecurring(fd){await pool.query('UPDATE recurring_items SET active=NOT active WHERE id=$1',[n(fd.get('id'))]);done()}
export async function deleteRecurring(fd){await pool.query('DELETE FROM recurring_items WHERE id=$1',[n(fd.get('id'))]);done()}
export async function addGoal(fd){await pool.query('INSERT INTO savings_goals(name,target_amount,current_amount,target_date) VALUES($1,$2,$3,$4)',[s(fd.get('name')),positive(fd.get('target_amount'),'Objetivo'),nonNegative(fd.get('current_amount'),'Ahorrado'),validDate(fd.get('target_date'),{optional:true})]);done()}
export async function updateGoal(fd){await pool.query('UPDATE savings_goals SET current_amount=$1,target_amount=$2,target_date=$3 WHERE id=$4',[nonNegative(fd.get('current_amount'),'Ahorrado'),n(fd.get('target_amount')),validDate(fd.get('target_date'),{optional:true}),n(fd.get('id'))]);done()}
export async function deleteGoal(fd){await pool.query('DELETE FROM savings_goals WHERE id=$1',[n(fd.get('id'))]);done()}
export async function importCsv(fd){const raw=s(fd.get('csv'));if(!raw)return;const lines=raw.split(/\r?\n/).filter(Boolean),header=lines.shift()?.toLowerCase().split(',').map(x=>x.trim())||[];for(const line of lines){const v=line.split(',').map(x=>x.trim().replace(/^"|"$/g,'')),row=Object.fromEntries(header.map((h,i)=>[h,v[i]||'']));if(row.tipo==='ingreso')await pool.query('INSERT INTO income(concept,source,amount,occurred_on,status) VALUES($1,$2,$3,$4,$5)',[row.concepto,row.origen||'extra',positive(row.monto),validDate(row.fecha),row.estado||'pagado']);if(row.tipo==='gasto')await pool.query('INSERT INTO expense(concept,category,amount,occurred_on,status) VALUES($1,$2,$3,$4,$5)',[row.concepto,row.categoria||'Otros',positive(row.monto),validDate(row.fecha),row.estado||'pagado']);}done()}

export async function addAccount(fd){await pool.query('INSERT INTO accounts(name,kind,opening_balance) VALUES($1,$2,$3)',[required(fd.get('name'),'Cuenta'),s(fd.get('kind'))||'bank',n(fd.get('opening_balance')||0)]);done()}
export async function addCard(fd){await pool.query('INSERT INTO credit_cards(name,closing_day,due_day,account_id) VALUES($1,$2,$3,$4)',[required(fd.get('name'),'Tarjeta'),n(fd.get('closing_day')),n(fd.get('due_day')),fd.get('account_id')?n(fd.get('account_id')):null]);done()}
export async function addTransfer(fd){const a=n(fd.get('from_account_id')),b=n(fd.get('to_account_id'));if(a===b)throw new Error('Las cuentas deben ser diferentes');await pool.query('INSERT INTO transfers(from_account_id,to_account_id,amount,occurred_on,notes) VALUES($1,$2,$3,$4,$5)',[a,b,positive(fd.get('amount')),validDate(fd.get('occurred_on')),s(fd.get('notes'))||null]);done()}
export async function addDebt(fd){const amount=positive(fd.get('original_amount'),'Deuda');await pool.query('INSERT INTO debts(name,lender,original_amount,current_balance,installment_amount,due_date) VALUES($1,$2,$3,$3,$4,$5)',[required(fd.get('name'),'Deuda'),s(fd.get('lender'))||null,amount,fd.get('installment_amount')?positive(fd.get('installment_amount'),'Cuota'):null,validDate(fd.get('due_date'),{optional:true})]);done()}
export async function payDebt(fd){const id=n(fd.get('debt_id')),amount=positive(fd.get('amount'));await pool.query('BEGIN');try{const r=await pool.query('SELECT current_balance FROM debts WHERE id=$1 FOR UPDATE',[id]);if(!r.rows[0])throw new Error('Deuda inválida');const applied=Math.min(amount,Number(r.rows[0].current_balance));await pool.query('INSERT INTO debt_payments(debt_id,amount,paid_on) VALUES($1,$2,$3)',[id,applied,validDate(fd.get('paid_on'))]);await pool.query("UPDATE debts SET current_balance=GREATEST(0,current_balance-$1),status=CASE WHEN current_balance-$1<=0 THEN 'paid' ELSE 'active' END WHERE id=$2",[applied,id]);await pool.query('COMMIT')}catch(e){await pool.query('ROLLBACK');throw e}done()}
export async function addTag(fd){await pool.query('INSERT INTO tags(name) VALUES($1) ON CONFLICT(name) DO NOTHING',[required(fd.get('name'),'Etiqueta')]);done()}
export async function closeMonth(fd){const y=n(fd.get('view_year')),m=n(fd.get('view_month')),from=`${y}-${String(m).padStart(2,'0')}-01`,to=new Date(Date.UTC(y,m,1)).toISOString().slice(0,10);const [i,e]=await Promise.all([pool.query('SELECT COALESCE(SUM(amount),0) t FROM income WHERE deleted_at IS NULL AND occurred_on >= $1 AND occurred_on < $2',[from,to]),pool.query('SELECT COALESCE(SUM(amount),0) t FROM expense WHERE deleted_at IS NULL AND occurred_on >= $1 AND occurred_on < $2',[from,to])]);const income=Number(i.rows[0].t),expense=Number(e.rows[0].t);await pool.query(`INSERT INTO monthly_closures(year,month,income,expense,balance,snapshot) VALUES($1,$2,$3,$4,$5,$6::jsonb) ON CONFLICT(year,month) DO UPDATE SET income=EXCLUDED.income,expense=EXCLUDED.expense,balance=EXCLUDED.balance,snapshot=EXCLUDED.snapshot,closed_at=NOW()`,[y,m,income,expense,income-expense,JSON.stringify({income,expense,balance:income-expense})]);done()}
export async function addExpenseAdvanced(fd){const concept=required(fd.get('concept'),'Concepto'),category=required(fd.get('category'),'Categoría'),amount=positive(fd.get('amount')),occurred=validDate(fd.get('occurred_on')),st=status(fd.get('status')||'pagado'),account=fd.get('account_id')?n(fd.get('account_id')):null,card=fd.get('credit_card_id')?n(fd.get('credit_card_id')):null,total=Math.max(1,Math.min(60,n(fd.get('installments')||1))),tags=s(fd.get('tags')).split(',').map(x=>x.trim()).filter(Boolean);await pool.query('BEGIN');try{const group=total>1?(await pool.query('SELECT gen_random_uuid() id')).rows[0].id:null;for(let k=0;k<total;k++){const d=new Date(occurred+'T00:00:00Z');d.setUTCMonth(d.getUTCMonth()+k);const dt=d.toISOString().slice(0,10),part=Math.round(amount/total*100)/100;const r=await pool.query('INSERT INTO expense(concept,category,amount,occurred_on,status,account_id,credit_card_id,installment_group,installment_number,installment_total) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id',[total>1?`${concept} (${k+1}/${total})`:concept,category,part,dt,st,account,card,group,total>1?k+1:null,total>1?total:null]);if(k===0)for(const tag of tags){const tr=await pool.query('INSERT INTO tags(name) VALUES($1) ON CONFLICT(name) DO UPDATE SET name=EXCLUDED.name RETURNING id',[tag]);await pool.query("INSERT INTO movement_tags(movement_kind,movement_id,tag_id) VALUES('expense',$1,$2) ON CONFLICT DO NOTHING",[r.rows[0].id,tr.rows[0].id])}}await pool.query('COMMIT')}catch(e){await pool.query('ROLLBACK');throw e}done()}
export async function addReceipt(fd){const file=fd.get('receipt');if(!file||typeof file.arrayBuffer!=='function'||!file.size)throw new Error('Comprobante es obligatorio');if(file.size>5*1024*1024)throw new Error('El comprobante supera 5 MB');const kind=s(fd.get('movement_kind')),id=n(fd.get('movement_id'));if(!['income','expense'].includes(kind))throw new Error('Movimiento inválido');await pool.query('INSERT INTO receipts(movement_kind,movement_id,file_name,mime_type,data) VALUES($1,$2,$3,$4,$5)',[kind,id,s(file.name)||'comprobante',s(file.type)||'application/octet-stream',Buffer.from(await file.arrayBuffer())]);done()}
