'use server';
import { pool } from '../lib/db';
import { revalidatePath } from 'next/cache';
const done=()=>revalidatePath('/'),s=v=>String(v??'').trim();
const n=v=>{const x=Number(v);if(!Number.isFinite(x))throw new Error('Monto o valor numérico inválido');return x};
const required=(v,label)=>{const x=s(v);if(!x)throw new Error(`${label} es obligatorio`);return x};
const validDate=(v,{optional=false}={})=>{const x=s(v);if(!x&&optional)return null;if(!/^\d{4}-\d{2}-\d{2}$/.test(x)||Number.isNaN(Date.parse(x+'T00:00:00Z')))throw new Error('Fecha inválida');return x};
const status=v=>{const x=s(v);if(!['pagado','pendiente'].includes(x))throw new Error('Estado inválido');return x};
const positive=(v,label='Monto')=>{const x=n(v);if(x<=0)throw new Error(`${label} debe ser mayor a 0`);return x};
const nonNegative=(v,label='Monto')=>{const x=n(v);if(x<0)throw new Error(`${label} no puede ser negativo`);return x};
export async function addIncome(fd){await pool.query('INSERT INTO income(concept,source,amount,occurred_on,status) VALUES($1,$2,$3,$4,$5)',[required(fd.get('concept'),'Concepto'),s(fd.get('source'))||'extra',positive(fd.get('amount')),validDate(fd.get('occurred_on')),status(fd.get('status')||'pagado')]);done()}
export async function addExpense(fd){await pool.query('INSERT INTO expense(concept,category,amount,occurred_on,status) VALUES($1,$2,$3,$4,$5)',[required(fd.get('concept'),'Concepto'),s(fd.get('category')),positive(fd.get('amount')),date(fd.get('occurred_on')),status(fd.get('status')||'pagado')]);done()}
export async function updateIncome(fd){await pool.query('UPDATE income SET concept=$1,source=$2,amount=$3,occurred_on=$4,status=$5 WHERE id=$6',[required(fd.get('concept'),'Concepto'),s(fd.get('source')),positive(fd.get('amount')),validDate(fd.get('occurred_on')),status(fd.get('status')),n(fd.get('id'))]);done()}
export async function updateExpense(fd){await pool.query('UPDATE expense SET concept=$1,category=$2,amount=$3,occurred_on=$4,status=$5 WHERE id=$6',[required(fd.get('concept'),'Concepto'),s(fd.get('category')),positive(fd.get('amount')),validDate(fd.get('occurred_on')),status(fd.get('status')),n(fd.get('id'))]);done()}
export async function deleteIncome(fd){await pool.query('UPDATE income SET deleted_at=NOW() WHERE id=$1',[n(fd.get('id'))]);done()}
export async function deleteExpense(fd){await pool.query('UPDATE expense SET deleted_at=NOW() WHERE id=$1',[n(fd.get('id'))]);done()}
export async function restoreMovement(kind,id){const table=kind==='income'?'income':'expense';await pool.query(`UPDATE ${table} SET deleted_at=NULL WHERE id=$1`,[n(id)]);done()}
export async function duplicateMovement(kind,id){if(kind==='income')await pool.query(`INSERT INTO income(concept,source,amount,occurred_on,status) SELECT concept,source,amount,occurred_on,status FROM income WHERE id=$1`,[n(id)]);else await pool.query(`INSERT INTO expense(concept,category,amount,occurred_on,status) SELECT concept,category,amount,occurred_on,status FROM expense WHERE id=$1`,[n(id)]);done()}
export async function setBudget(fd){await pool.query(`INSERT INTO budgets(category_id,year,month,amount) VALUES($1,$2,$3,$4) ON CONFLICT(category_id,year,month) DO UPDATE SET amount=EXCLUDED.amount`,[n(fd.get('category_id')),n(fd.get('view_year')),n(fd.get('view_month')),nonNegative(fd.get('amount'),'Presupuesto')]);done()}
export async function setMonthlyBudget(fd){await pool.query(`INSERT INTO monthly_budgets(year,month,amount) VALUES($1,$2,$3) ON CONFLICT(year,month) DO UPDATE SET amount=EXCLUDED.amount`,[n(fd.get('view_year')),n(fd.get('view_month')),nonNegative(fd.get('amount'),'Presupuesto')]);done()}
export async function addCategory(fd){await pool.query('INSERT INTO categories(name,sort_order) VALUES($1,(SELECT COALESCE(MAX(sort_order),0)+1 FROM categories)) ON CONFLICT(name) DO UPDATE SET active=true',[required(fd.get('name'),'Categoría')]);done()}
export async function toggleCategory(fd){await pool.query('UPDATE categories SET active=NOT active WHERE id=$1',[n(fd.get('id'))]);done()}
export async function addRecurring(fd){await pool.query('INSERT INTO recurring_items(kind,concept,category,source,amount,day_of_month,status,start_date,end_date) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[s(fd.get('kind')),required(fd.get('concept'),'Concepto'),s(fd.get('category'))||null,s(fd.get('source'))||null,positive(fd.get('amount')),Math.min(28,Math.max(1,n(fd.get('day_of_month'))||1)),status(fd.get('status')||'pendiente'),validDate(fd.get('start_date'),{optional:true}),validDate(fd.get('end_date'),{optional:true})]);done()}
export async function updateRecurring(fd){await pool.query('UPDATE recurring_items SET concept=$1,amount=$2,day_of_month=$3,status=$4,start_date=$5,end_date=$6 WHERE id=$7',[required(fd.get('concept'),'Concepto'),positive(fd.get('amount')),n(fd.get('day_of_month')),status(fd.get('status')),validDate(fd.get('start_date'),{optional:true}),validDate(fd.get('end_date'),{optional:true}),n(fd.get('id'))]);done()}
export async function toggleRecurring(fd){await pool.query('UPDATE recurring_items SET active=NOT active WHERE id=$1',[n(fd.get('id'))]);done()}
export async function deleteRecurring(fd){await pool.query('DELETE FROM recurring_items WHERE id=$1',[n(fd.get('id'))]);done()}
export async function addGoal(fd){await pool.query('INSERT INTO savings_goals(name,target_amount,current_amount,target_date) VALUES($1,$2,$3,$4)',[s(fd.get('name')),positive(fd.get('target_amount'),'Objetivo'),nonNegative(fd.get('current_amount'),'Ahorrado'),validDate(fd.get('target_date'),{optional:true})]);done()}
export async function updateGoal(fd){await pool.query('UPDATE savings_goals SET current_amount=$1,target_amount=$2,target_date=$3 WHERE id=$4',[nonNegative(fd.get('current_amount'),'Ahorrado'),n(fd.get('target_amount')),validDate(fd.get('target_date'),{optional:true}),n(fd.get('id'))]);done()}
export async function deleteGoal(fd){await pool.query('DELETE FROM savings_goals WHERE id=$1',[n(fd.get('id'))]);done()}
export async function importCsv(fd){const raw=s(fd.get('csv'));if(!raw)return;const lines=raw.split(/\r?\n/).filter(Boolean),header=lines.shift()?.toLowerCase().split(',').map(x=>x.trim())||[];for(const line of lines){const v=line.split(',').map(x=>x.trim().replace(/^"|"$/g,'')),row=Object.fromEntries(header.map((h,i)=>[h,v[i]||'']));if(row.tipo==='ingreso')await pool.query('INSERT INTO income(concept,source,amount,occurred_on,status) VALUES($1,$2,$3,$4,$5)',[row.concepto,row.origen||'extra',positive(row.monto),validDate(row.fecha),row.estado||'pagado']);if(row.tipo==='gasto')await pool.query('INSERT INTO expense(concept,category,amount,occurred_on,status) VALUES($1,$2,$3,$4,$5)',[row.concepto,row.categoria||'Otros',positive(row.monto),validDate(row.fecha),row.estado||'pagado']);}done()}
