import SectionModal from './SectionModal';
import SafeForm from './SafeForm';
import {addAccount,addCard,addTransfer,addDebt,payDebt,addTag,closeMonth,addReceipt} from './actions';
const money=n=>new Intl.NumberFormat('es-UY',{style:'currency',currency:'UYU',maximumFractionDigits:0}).format(Number(n||0));
const Hidden=({y,m})=><><input type="hidden" name="view_year" value={y}/><input type="hidden" name="view_month" value={m}/></>;
export default function AdvancedFinance({accounts,cards,debts,tags,upcoming,year,month,selectedDate,forecast,closure}){
 return <section className="section-block compact-section"><div className="section-head"><div><span className="eyebrow">FINANZAS AVANZADAS</span><h2>Cuentas, tarjetas y planificación</h2></div></div>
 <div className="smart-kpis"><div className="card"><small>Proyección 30 días</small><b>{money(forecast.d30)}</b></div><div className="card"><small>Proyección 60 días</small><b>{money(forecast.d60)}</b></div><div className="card"><small>Proyección 90 días</small><b>{money(forecast.d90)}</b></div></div>
 <div className="section-modal-grid">
 <SectionModal eyebrow="DINERO" title="Cuentas y medios de pago"><SafeForm action={addAccount} className="stack"><input name="name" placeholder="Nombre de cuenta" required/><select name="kind" required><option value="bank">Banco</option><option value="cash">Efectivo</option><option value="debit">Débito</option><option value="other">Otro</option></select><input name="opening_balance" type="number" step=".01" defaultValue="0"/><button>Crear cuenta</button></SafeForm>{accounts.map(a=><div className="finance-row" key={a.id}><b>{a.name}</b><span>{a.kind} · saldo inicial {money(a.opening_balance)}</span></div>)}</SectionModal>
 <SectionModal eyebrow="CRÉDITO" title="Tarjetas de crédito"><SafeForm action={addCard} className="stack"><input name="name" placeholder="Tarjeta" required/><input name="closing_day" type="number" min="1" max="31" placeholder="Día de cierre" required/><input name="due_day" type="number" min="1" max="31" placeholder="Día de vencimiento" required/><select name="account_id"><option value="">Cuenta de pago opcional</option>{accounts.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select><button>Agregar tarjeta</button></SafeForm>{cards.map(c=><div className="finance-row" key={c.id}><b>{c.name}</b><span>Cierra día {c.closing_day} · vence día {c.due_day}</span></div>)}</SectionModal>
 <SectionModal eyebrow="MOVIMIENTO INTERNO" title="Transferencias"><SafeForm action={addTransfer} className="stack"><select name="from_account_id" required><option value="">Desde</option>{accounts.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select><select name="to_account_id" required><option value="">Hacia</option>{accounts.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select><input name="amount" type="number" min=".01" step=".01" placeholder="Monto" required/><input name="occurred_on" type="date" defaultValue={selectedDate} required/><input name="notes" placeholder="Nota opcional"/><button>Transferir</button></SafeForm><p className="muted">Las transferencias no cuentan como ingreso ni gasto.</p></SectionModal>
 <SectionModal eyebrow="OBLIGACIONES" title="Deudas y préstamos" wide><SafeForm action={addDebt} className="stack"><input name="name" placeholder="Nombre de deuda" required/><input name="lender" placeholder="Persona / entidad"/><input name="original_amount" type="number" min=".01" step=".01" placeholder="Monto original" required/><input name="installment_amount" type="number" min=".01" step=".01" placeholder="Cuota opcional"/><input name="due_date" type="date"/><button>Registrar deuda</button></SafeForm>{debts.map(d=><div className="debt-card" key={d.id}><div><b>{d.name}</b><span>{d.lender||'Sin entidad'} · saldo {money(d.current_balance)} de {money(d.original_amount)}</span></div>{d.status==='active'&&<SafeForm action={payDebt} className="mini"><input type="hidden" name="debt_id" value={d.id}/><input name="amount" type="number" min=".01" step=".01" placeholder="Pago" required/><input name="paid_on" type="date" defaultValue={selectedDate} required/><button>Registrar pago</button></SafeForm>}</div>)}</SectionModal>
 <SectionModal eyebrow="ORGANIZACIÓN" title="Etiquetas"><SafeForm action={addTag} className="mini"><input name="name" placeholder="Ej. Viaje" required/><button>Agregar</button></SafeForm><div className="tag-cloud">{tags.map(t=><span key={t.id}>#{t.name}</span>)}</div></SectionModal>
 <SectionModal eyebrow="CALENDARIO" title="Próximos compromisos" wide>{upcoming.length?upcoming.map((x,i)=><div className="calendar-item" key={i}><b>{String(x.date).slice(0,10)}</b><span>{x.label}</span><strong>{money(x.amount)}</strong></div>):<p className="muted">No hay compromisos próximos registrados.</p>}</SectionModal>
 <SectionModal eyebrow="COMPROBANTES" title="Adjuntar comprobante"><SafeForm action={addReceipt} className="stack" encType="multipart/form-data"><select name="movement_kind" required><option value="expense">Gasto</option><option value="income">Ingreso</option></select><input name="movement_id" type="number" min="1" placeholder="ID del movimiento" required/><input name="receipt" type="file" accept="image/*,.pdf" required/><small className="muted">Máximo 5 MB.</small><button>Adjuntar</button></SafeForm></SectionModal>
 <SectionModal eyebrow="CIERRE" title="Cierre mensual"><p>{closure?<>Cierre guardado: <b>{money(closure.balance)}</b> · {String(closure.closed_at).slice(0,10)}</>:<>Guarda una fotografía de los totales de {month}/{year}.</>}</p><SafeForm action={closeMonth} className="stack"><Hidden y={year} m={month}/><button>{closure?'Actualizar cierre':'Cerrar mes'}</button></SafeForm></SectionModal>
 </div></section>
}