import { pool } from '../lib/db';
import ThemeToggle from './ThemeToggle';
import Movements from './Movements';
import QuickAdd from './QuickAdd';
import SectionModal from './SectionModal';
import {addIncome,addExpense,updateIncome,updateExpense,deleteIncome,deleteExpense,setBudget,addCategory,toggleCategory,addRecurring,updateRecurring,toggleRecurring,deleteRecurring,setMonthlyBudget,addGoal,updateGoal,deleteGoal,importCsv} from './actions';
const money=n=>new Intl.NumberFormat('es-UY',{style:'currency',currency:'UYU',maximumFractionDigits:0}).format(Number(n||0));
const dv=v=>typeof v==='string'?v.slice(0,10):new Date(v).toISOString().slice(0,10);
const months=['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'];
const Hidden=({y,m})=><><input type="hidden" name="view_year" value={y}/><input type="hidden" name="view_month" value={m}/></>;

async function materializeRecurring(year,month){
 const key=`${year}-${String(month).padStart(2,'0')}`, first=`${key}-01`, items=(await pool.query('SELECT * FROM recurring_items WHERE active=true AND (start_date IS NULL OR start_date <= $1) AND (end_date IS NULL OR end_date >= $1)',[first])).rows;
 const days=new Date(year,month,0).getDate();
 for(const r of items){const date=`${key}-${String(Math.min(r.day_of_month,days)).padStart(2,'0')}`;
  if(r.kind==='income') await pool.query(`INSERT INTO income(concept,source,amount,occurred_on,status,recurring_id,period_key) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(recurring_id,period_key) WHERE recurring_id IS NOT NULL DO NOTHING`,[r.concept,r.source||'extra',r.amount,date,r.status,r.id,key]);
  else await pool.query(`INSERT INTO expense(concept,category,amount,occurred_on,status,recurring_id,period_key) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(recurring_id,period_key) WHERE recurring_id IS NOT NULL DO NOTHING`,[r.concept,r.category||'Otros',r.amount,date,r.status,r.id,key]);
 }
}

export default async function Dashboard({params}){
 const now=new Date(),year=Number(params?.year||now.getFullYear()),month=Number(params?.month||now.getMonth()+1);
 await materializeRecurring(year,month);
 const from=`${year}-${String(month).padStart(2,'0')}-01`,to=new Date(Date.UTC(year,month,1)).toISOString().slice(0,10);
 const prevDate=new Date(Date.UTC(year,month-2,1)),pf=prevDate.toISOString().slice(0,10),pt=from;
 const q=String(params?.q||'').trim(),cat=String(params?.category||''),status=String(params?.status||'');
 const [inc,exp,prevInc,prevExp,cats,budgets,monthlyBudget,recurring,goals,annual,monthSeries]=await Promise.all([
  pool.query(`SELECT * FROM income WHERE deleted_at IS NULL AND occurred_on >= $1 AND occurred_on < $2 AND ($3='' OR concept ILIKE '%'||$3||'%') AND ($4='' OR status=$4) ORDER BY occurred_on DESC,id DESC`,[from,to,q,status]),
  pool.query(`SELECT * FROM expense WHERE deleted_at IS NULL AND occurred_on >= $1 AND occurred_on < $2 AND ($3='' OR concept ILIKE '%'||$3||'%') AND ($4='' OR category=$4) AND ($5='' OR status=$5) ORDER BY occurred_on DESC,id DESC`,[from,to,q,cat,status]),
  pool.query('SELECT COALESCE(SUM(amount),0) total FROM income WHERE deleted_at IS NULL AND occurred_on >= $1 AND occurred_on < $2',[pf,pt]),
  pool.query('SELECT COALESCE(SUM(amount),0) total FROM expense WHERE deleted_at IS NULL AND occurred_on >= $1 AND occurred_on < $2',[pf,pt]),
  pool.query('SELECT * FROM categories ORDER BY sort_order,name'),
  pool.query('SELECT b.*,c.name category FROM budgets b JOIN categories c ON c.id=b.category_id WHERE year=$1 AND month=$2',[year,month]),
  pool.query('SELECT amount FROM monthly_budgets WHERE year=$1 AND month=$2',[year,month]),
  pool.query('SELECT * FROM recurring_items ORDER BY kind,concept'),
  pool.query('SELECT * FROM savings_goals ORDER BY id DESC'),
  pool.query(`SELECT COALESCE((SELECT SUM(amount) FROM income WHERE deleted_at IS NULL AND EXTRACT(YEAR FROM occurred_on)=$1),0) income,COALESCE((SELECT SUM(amount) FROM expense WHERE deleted_at IS NULL AND EXTRACT(YEAR FROM occurred_on)=$1),0) expense`,[year]),
  pool.query(`WITH m AS(SELECT generate_series(1,12)m) SELECT m.m,COALESCE((SELECT SUM(amount) FROM income i WHERE i.deleted_at IS NULL AND EXTRACT(YEAR FROM i.occurred_on)=$1 AND EXTRACT(MONTH FROM i.occurred_on)=m.m),0) income,COALESCE((SELECT SUM(amount) FROM expense e WHERE e.deleted_at IS NULL AND EXTRACT(YEAR FROM e.occurred_on)=$1 AND EXTRACT(MONTH FROM e.occurred_on)=m.m),0) expense FROM m ORDER BY m.m`,[year])
 ]);
 const allCats=cats.rows.filter(x=>x.active),income=inc.rows.reduce((a,x)=>a+Number(x.amount),0),expense=exp.rows.reduce((a,x)=>a+Number(x.amount),0);
 const paidIncome=inc.rows.filter(x=>x.status==='pagado').reduce((a,x)=>a+Number(x.amount),0),paidExpense=exp.rows.filter(x=>x.status==='pagado').reduce((a,x)=>a+Number(x.amount),0);
 const pendingIncome=income-paidIncome,pendingExpense=expense-paidExpense,projected=paidIncome+pendingIncome-paidExpense-pendingExpense;
 const pi=Number(prevInc.rows[0].total),pe=Number(prevExp.rows[0].total),pct=(a,b)=>b?((a-b)/b*100):0;
 const spendBy=Object.fromEntries(allCats.map(c=>[c.name,exp.rows.filter(x=>x.category===c.name).reduce((a,x)=>a+Number(x.amount),0)]));
 const savingsRate=income>0?(income-expense)/income*100:0;
 const topCategory=Object.entries(spendBy).sort((a,b)=>b[1]-a[1])[0]||['Sin gastos',0];
 const budgetAlerts=budgets.rows.map(b=>({category:b.category,limit:Number(b.amount),spent:Number(spendBy[b.category]||0)})).filter(x=>x.limit>0&&x.spent/x.limit>=.8).sort((a,b)=>(b.spent/b.limit)-(a.spent/a.limit));
 const expenseChange=pct(expense,pe);
 const analysisItems=[
  income===0?{tone:'warn',title:'Sin ingresos registrados',text:'No hay ingresos cargados para este período.'}:savingsRate>=20?{tone:'good',title:'Buen nivel de ahorro',text:`Estás conservando ${savingsRate.toFixed(1)}% de tus ingresos este mes.`}:savingsRate>=0?{tone:'warn',title:'Margen de ahorro bajo',text:`Tu ahorro del período es ${savingsRate.toFixed(1)}% de los ingresos.`}:{tone:'bad',title:'Gastas más de lo que ingresa',text:`El déficit del período es ${money(Math.abs(income-expense))}.`},
  {tone:expenseChange>10?'bad':expenseChange>0?'warn':'good',title:'Gastos vs. mes anterior',text:pe?`${expenseChange>=0?'Subieron':'Bajaron'} ${Math.abs(expenseChange).toFixed(1)}% respecto al mes anterior.`:'No hay suficiente historial anterior para comparar.'},
  {tone:'info',title:'Mayor categoría de gasto',text:topCategory[1]>0?`${topCategory[0]} concentra ${money(topCategory[1])} del gasto del período.`:'Todavía no hay gastos registrados.'},
  pendingExpense>0?{tone:'warn',title:'Pagos pendientes',text:`Tienes ${money(pendingExpense)} marcado como pendiente de pago.`}:{tone:'good',title:'Sin pagos pendientes',text:'No tienes gastos pendientes en el período.'}
 ];
 const selectedDate=year===now.getFullYear()&&month===now.getMonth()+1?now.toISOString().slice(0,10):from;
 return <main className="wrap">
  <div className="hero"><div><div className="muted">FINANZAS PERSONALES</div><h1>Gestor de gastos</h1><div className="period-badge">{months[month-1]} {year}</div></div>
   <div className="hero-actions"><ThemeToggle/><form className="filters"><select name="month" defaultValue={month}>{months.map((x,i)=><option value={i+1} key={x}>{x}</option>)}</select><select name="year" defaultValue={year}>{Array.from({length:11},(_,i)=>year-5+i).map(y=><option key={y}>{y}</option>)}</select><button>Ver período</button></form></div>
  </div>
  <section className="grid kpis"><div className="card kpi"><span>Ingresos</span><strong className="positive">{money(income)}</strong><small>{pct(income,pi).toFixed(1)}% vs mes anterior</small></div><div className="card kpi"><span>Gastos</span><strong className="negative">{money(expense)}</strong><small>{pct(expense,pe).toFixed(1)}% vs mes anterior</small></div><div className="card kpi"><span>Balance</span><strong>{money(income-expense)}</strong></div><div className="card kpi"><span>Pendiente de pagar</span><strong>{money(pendingExpense)}</strong></div><div className="card kpi"><span>Balance proyectado</span><strong>{money(projected)}</strong></div></section>
  <section className="analysis-section"><div className="section-head"><div><span className="eyebrow">ANÁLISIS DEL MES</span><h2>Lectura rápida de tus finanzas</h2></div></div><div className="analysis-grid">{analysisItems.map((a,i)=><div className={`analysis-card ${a.tone}`} key={i}><b>{a.title}</b><p>{a.text}</p></div>)}</div>{budgetAlerts.length>0&&<div className="budget-alert"><b>Atención a presupuestos</b><span>{budgetAlerts.slice(0,3).map(x=>`${x.category}: ${(x.spent/x.limit*100).toFixed(0)}%`).join(' · ')}</span></div>}</section>
  {expense>0&&<section className="category-visual"><div className="card"><div className="section-head"><div><span className="eyebrow">DISTRIBUCIÓN</span><h2>¿Dónde se va el dinero?</h2></div></div><div className="category-bars">{Object.entries(spendBy).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([name,value])=><div className="category-bar" key={name}><div><b>{name}</b><span>{money(value)} · {(value/expense*100).toFixed(0)}%</span></div><div className="bar"><span style={{width:`${Math.min(100,value/expense*100)}%`}}/></div></div>)}</div></div></section>}
  <div className="card toolbar"><form className="filters"><Hidden y={year} m={month}/><input name="q" placeholder="Buscar concepto" defaultValue={q}/><select name="category" defaultValue={cat}><option value="">Todas las categorías</option>{allCats.map(c=><option key={c.id}>{c.name}</option>)}</select><select name="status" defaultValue={status}><option value="">Todos</option><option value="pagado">Pagado</option><option value="pendiente">Pendiente</option></select><button>Filtrar</button></form><div className="export-group"><a className="export-btn" href={`/api/export?year=${year}&month=${month}`}>CSV</a><a className="export-btn" href={`/api/export/excel?year=${year}&month=${month}`}>Excel</a><a className="export-btn" href={`/api/export/pdf?year=${year}&month=${month}`}>PDF</a></div></div>
  <nav className="section-nav"><a href="#movimientos">Movimientos</a><a href="#presupuestos">Presupuestos</a><a href="#planificacion">Planificación</a><a href="#anual">Resumen anual</a><a href="#herramientas">Herramientas</a></nav>
  <QuickAdd categories={allCats} year={year} month={month} selectedDate={selectedDate}/>
  <section id="movimientos" className="section-block"><div className="section-head"><div><span className="eyebrow">MOVIMIENTOS</span><h2>Todos los movimientos · {months[month-1]} {year}</h2></div><span className="muted">Edita, duplica o elimina sin salir de la lista</span></div><Movements income={inc.rows} expenses={exp.rows} categories={allCats} year={year} month={month}/></section>
  <section id="presupuestos" className="section-block compact-section"><div className="section-head"><div><span className="eyebrow">CONTROL</span><h2>Presupuestos y categorías</h2></div></div>
   <div className="card monthly-budget"><div><span className="eyebrow">LÍMITE GENERAL</span><h3>Presupuesto mensual</h3><p className="muted">Gastado {money(expense)} · {monthlyBudget.rows[0]?money(Math.max(0,Number(monthlyBudget.rows[0].amount)-expense))+' disponible':'Define tu límite del mes'}</p></div><form action={setMonthlyBudget} className="mini"><Hidden y={year} m={month}/><input name="amount" type="number" step=".01" min="0" placeholder="Límite mensual" required defaultValue={monthlyBudget.rows[0]?Number(monthlyBudget.rows[0].amount):''}/><button>Guardar</button></form></div>
   <div className="section-modal-grid">
    <SectionModal eyebrow="LÍMITES" title="Presupuesto por categoría" wide>{allCats.map(c=>{const b=budgets.rows.find(x=>Number(x.category_id)===Number(c.id)),spent=spendBy[c.name]||0,limit=Number(b?.amount||0),p=limit?spent/limit*100:0;return <div className="budget" key={c.id}><div><b>{c.name}</b> {money(spent)} / {limit?money(limit):'Sin límite'} {limit&&<span>{p.toFixed(0)}%</span>}</div>{limit>0&&<div className="bar"><span style={{width:`${Math.min(p,100)}%`}}/></div>}<form action={setBudget} className="mini"><Hidden y={year} m={month}/><input type="hidden" name="category_id" value={c.id}/><input name="amount" type="number" step=".01" min="0" defaultValue={limit||''} placeholder="Presupuesto" required/><button>Guardar</button></form></div>})}</SectionModal>
    <SectionModal eyebrow="CONFIGURACIÓN" title="Categorías"><form action={addCategory} className="mini"><Hidden y={year} m={month}/><input name="name" placeholder="Nueva categoría" required/><button>Agregar</button></form>{cats.rows.map(c=><form action={toggleCategory} className="category-row" key={c.id}><Hidden y={year} m={month}/><input type="hidden" name="id" value={c.id}/><span>{c.name}</span><button>{c.active?'Desactivar':'Activar'}</button></form>)}</SectionModal>
   </div>
  </section>
  <section id="planificacion" className="section-block compact-section"><div className="section-head"><div><span className="eyebrow">PLANIFICACIÓN</span><h2>Recurrentes y metas</h2></div></div><div className="section-modal-grid">
   <SectionModal eyebrow="AUTOMÁTICO" title="Recurrentes" wide><form action={addRecurring} className="stack"><Hidden y={year} m={month}/><select name="kind"><option value="expense">Gasto</option><option value="income">Ingreso</option></select><input name="concept" placeholder="Concepto" required/><select name="category"><option value="">— Categoría —</option>{allCats.map(c=><option key={c.id}>{c.name}</option>)}</select><select name="source"><option value="">— Origen —</option><option value="sueldo">Sueldo</option><option value="comision">Comisión</option><option value="bonus">Bonus</option><option value="extra">Extra</option></select><input name="amount" type="number" step=".01" min="0.01" placeholder="Monto" required/><input name="day_of_month" type="number" min="1" max="28" placeholder="Día" required/><label><span className="muted">Desde</span><input name="start_date" type="date"/></label><label><span className="muted">Hasta</span><input name="end_date" type="date"/></label><select name="status"><option value="pendiente">Pendiente</option><option value="pagado">Pagado</option></select><button>Crear recurrente</button></form>{recurring.rows.map(r=><details className="recurring-row" key={r.id}><summary><span>{r.active?'●':'○'} {r.concept} · día {r.day_of_month} · {money(r.amount)}</span><b>{r.active?'Activo':'Pausado'}</b></summary><form action={updateRecurring} className="recurring-edit"><Hidden y={year} m={month}/><input type="hidden" name="id" value={r.id}/><input name="concept" defaultValue={r.concept} required/><input name="amount" type="number" step=".01" min="0.01" defaultValue={Number(r.amount)} required/><input name="day_of_month" type="number" min="1" max="28" defaultValue={r.day_of_month} required/><select name="status" defaultValue={r.status}><option value="pendiente">Pendiente</option><option value="pagado">Pagado</option></select><input name="start_date" type="date" defaultValue={r.start_date?dv(r.start_date):''}/><input name="end_date" type="date" defaultValue={r.end_date?dv(r.end_date):''}/><button>Guardar cambios</button></form><div className="recurring-actions"><form action={toggleRecurring}><Hidden y={year} m={month}/><input type="hidden" name="id" value={r.id}/><button>{r.active?'Pausar':'Reactivar'}</button></form><form action={deleteRecurring}><Hidden y={year} m={month}/><input type="hidden" name="id" value={r.id}/><button className="delete-btn">Eliminar</button></form></div></details>)}</SectionModal>
   <SectionModal eyebrow="AHORRO" title="Metas de ahorro"><form action={addGoal} className="stack"><Hidden y={year} m={month}/><input name="name" placeholder="Meta" required/><input name="target_amount" type="number" step=".01" min="0.01" placeholder="Objetivo" required/><input name="current_amount" type="number" step=".01" min="0" placeholder="Ahorrado" required/><input name="target_date" type="date"/><button>Crear meta</button></form>{goals.rows.map(g=><div className="goal" key={g.id}><b>{g.name}</b><div>{money(g.current_amount)} / {money(g.target_amount)} · {(Number(g.current_amount)/Number(g.target_amount)*100).toFixed(0)}%</div><div className="bar"><span style={{width:`${Math.min(100,Number(g.current_amount)/Number(g.target_amount)*100)}%`}}/></div><form action={updateGoal} className="mini"><Hidden y={year} m={month}/><input type="hidden" name="id" value={g.id}/><input name="current_amount" type="number" step=".01" min="0" defaultValue={Number(g.current_amount)} required/><input name="target_amount" type="hidden" value={Number(g.target_amount)}/><input name="target_date" type="hidden" value={g.target_date?dv(g.target_date):''}/><button>Actualizar</button></form><form action={deleteGoal}><Hidden y={year} m={month}/><input type="hidden" name="id" value={g.id}/><button className="delete-btn">Eliminar</button></form></div>)}</SectionModal>
  </div></section>
  <section id="anual" className="section-block compact-section"><div className="section-head"><div><span className="eyebrow">AÑO</span><h2>Resumen {year}</h2></div></div><SectionModal eyebrow="AÑO" title={`Ver resumen anual ${year}`} wide><h3>Evolución mensual</h3><div className="annual-chart">{monthSeries.rows.map((r,i)=>{const max=Math.max(...monthSeries.rows.flatMap(x=>[Number(x.income),Number(x.expense)]),1);return <div className="chart-month" key={r.m}><div className="chart-bars"><i className="income-bar" style={{height:`${Math.max(2,Number(r.income)/max*100)}%`}}/><i className="expense-bar" style={{height:`${Math.max(2,Number(r.expense)/max*100)}%`}}/></div><small>{months[i]}</small></div>})}</div><div className="chart-legend"><span>■ Ingresos</span><span>■ Gastos</span></div><h3>Detalle por mes</h3><div className="month-grid">{monthSeries.rows.map((r,i)=><div className="month-col" key={r.m}><b>{months[i]}</b><small className="positive">{money(r.income)}</small><small className="negative">{money(r.expense)}</small></div>)}</div><p>Ingresos anuales: <b>{money(annual.rows[0].income)}</b> · Gastos: <b>{money(annual.rows[0].expense)}</b> · Ahorro: <b>{money(Number(annual.rows[0].income)-Number(annual.rows[0].expense))}</b></p></SectionModal></section>
  <section id="herramientas" className="section-block compact-section"><SectionModal eyebrow="HERRAMIENTAS" title="Herramientas e importación"><h3>Importar CSV</h3><p className="muted">Columnas: tipo,fecha,concepto,categoria,origen,monto,estado</p><form action={importCsv} className="stack"><Hidden y={year} m={month}/><textarea name="csv" rows="6" required placeholder="tipo,fecha,concepto,categoria,origen,monto,estado&#10;gasto,2026-09-10,Supermercado,Alimentación,,2500,pagado"/><button>Importar</button></form></SectionModal></section>
 </main>
}