import { pool } from '../lib/db';
import {addIncome,addExpense,updateIncome,updateExpense,deleteIncome,deleteExpense,setBudget,addCategory,toggleCategory,addRecurring,deleteRecurring,addGoal,updateGoal,deleteGoal,importCsv} from './actions';
const money=n=>new Intl.NumberFormat('es-UY',{style:'currency',currency:'UYU',maximumFractionDigits:0}).format(Number(n||0));
const dv=v=>typeof v==='string'?v.slice(0,10):new Date(v).toISOString().slice(0,10);
const months=['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'];
const Hidden=({y,m})=><><input type="hidden" name="view_year" value={y}/><input type="hidden" name="view_month" value={m}/></>;

async function materializeRecurring(year,month){
 const key=`${year}-${String(month).padStart(2,'0')}`, items=(await pool.query('SELECT * FROM recurring_items WHERE active=true')).rows;
 const days=new Date(year,month,0).getDate();
 for(const r of items){const date=`${key}-${String(Math.min(r.day_of_month,days)).padStart(2,'0')}`;
  if(r.kind==='income') await pool.query(`INSERT INTO income(concept,source,amount,occurred_on,status,recurring_id,period_key) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(recurring_id,period_key) WHERE recurring_id IS NOT NULL DO NOTHING`,[r.concept,r.source||'extra',r.amount,date,r.status,r.id,key]);
  else await pool.query(`INSERT INTO expense(concept,category,amount,occurred_on,status,recurring_id,period_key) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(recurring_id,period_key) WHERE recurring_id IS NOT NULL DO NOTHING`,[r.concept,r.category||'Otros',r.amount,date,r.status,r.id,key]);
 }
}

export default async function Dashboard({params}){
 const now=new Date(),year=Number(params?.year||now.getFullYear()),month=Number(params?.month||now.getMonth()+1);
 await materializeRecurring(year,month);
 const from=`${year}-${String(month).padStart(2,'0')}-01`,to=new Date(Date.UTC(year,month,1)).toISOString().slice(0,10);
 const prevDate=new Date(Date.UTC(year,month-2,1)),pf=prevDate.toISOString().slice(0,10),pt=from;
 const q=String(params?.q||'').trim(),cat=String(params?.category||''),status=String(params?.status||'');
 const [inc,exp,prevInc,prevExp,cats,budgets,recurring,goals,annual,monthSeries]=await Promise.all([
  pool.query(`SELECT * FROM income WHERE occurred_on >= $1 AND occurred_on < $2 AND ($3='' OR concept ILIKE '%'||$3||'%') AND ($4='' OR status=$4) ORDER BY occurred_on DESC,id DESC`,[from,to,q,status]),
  pool.query(`SELECT * FROM expense WHERE occurred_on >= $1 AND occurred_on < $2 AND ($3='' OR concept ILIKE '%'||$3||'%') AND ($4='' OR category=$4) AND ($5='' OR status=$5) ORDER BY occurred_on DESC,id DESC`,[from,to,q,cat,status]),
  pool.query('SELECT COALESCE(SUM(amount),0) total FROM income WHERE occurred_on >= $1 AND occurred_on < $2',[pf,pt]),
  pool.query('SELECT COALESCE(SUM(amount),0) total FROM expense WHERE occurred_on >= $1 AND occurred_on < $2',[pf,pt]),
  pool.query('SELECT * FROM categories ORDER BY sort_order,name'),
  pool.query('SELECT b.*,c.name category FROM budgets b JOIN categories c ON c.id=b.category_id WHERE year=$1 AND month=$2',[year,month]),
  pool.query('SELECT * FROM recurring_items ORDER BY kind,concept'),
  pool.query('SELECT * FROM savings_goals ORDER BY id DESC'),
  pool.query(`SELECT COALESCE((SELECT SUM(amount) FROM income WHERE EXTRACT(YEAR FROM occurred_on)=$1),0) income,COALESCE((SELECT SUM(amount) FROM expense WHERE EXTRACT(YEAR FROM occurred_on)=$1),0) expense`,[year]),
  pool.query(`WITH m AS(SELECT generate_series(1,12)m) SELECT m.m,COALESCE((SELECT SUM(amount) FROM income i WHERE EXTRACT(YEAR FROM i.occurred_on)=$1 AND EXTRACT(MONTH FROM i.occurred_on)=m.m),0) income,COALESCE((SELECT SUM(amount) FROM expense e WHERE EXTRACT(YEAR FROM e.occurred_on)=$1 AND EXTRACT(MONTH FROM e.occurred_on)=m.m),0) expense FROM m ORDER BY m.m`,[year])
 ]);
 const allCats=cats.rows.filter(x=>x.active),income=inc.rows.reduce((a,x)=>a+Number(x.amount),0),expense=exp.rows.reduce((a,x)=>a+Number(x.amount),0);
 const paidIncome=inc.rows.filter(x=>x.status==='pagado').reduce((a,x)=>a+Number(x.amount),0),paidExpense=exp.rows.filter(x=>x.status==='pagado').reduce((a,x)=>a+Number(x.amount),0);
 const pendingIncome=income-paidIncome,pendingExpense=expense-paidExpense,projected=paidIncome+pendingIncome-paidExpense-pendingExpense;
 const pi=Number(prevInc.rows[0].total),pe=Number(prevExp.rows[0].total),pct=(a,b)=>b?((a-b)/b*100):0;
 const spendBy=Object.fromEntries(allCats.map(c=>[c.name,exp.rows.filter(x=>x.category===c.name).reduce((a,x)=>a+Number(x.amount),0)]));
 const selectedDate=year===now.getFullYear()&&month===now.getMonth()+1?now.toISOString().slice(0,10):from;
 return <main className="wrap">
  <div className="hero"><div><div className="muted">FINANZAS PERSONALES</div><h1>Gestor de gastos</h1><div className="period-badge">{months[month-1]} {year}</div></div>
   <form className="filters"><select name="month" defaultValue={month}>{months.map((x,i)=><option value={i+1} key={x}>{x}</option>)}</select><select name="year" defaultValue={year}>{Array.from({length:11},(_,i)=>year-5+i).map(y=><option key={y}>{y}</option>)}</select><button>Ver período</button></form>
  </div>
  <section className="grid kpis"><div className="card kpi"><span>Ingresos</span><strong className="positive">{money(income)}</strong><small>{pct(income,pi).toFixed(1)}% vs mes anterior</small></div><div className="card kpi"><span>Gastos</span><strong className="negative">{money(expense)}</strong><small>{pct(expense,pe).toFixed(1)}% vs mes anterior</small></div><div className="card kpi"><span>Balance</span><strong>{money(income-expense)}</strong></div><div className="card kpi"><span>Pendiente de pagar</span><strong>{money(pendingExpense)}</strong></div><div className="card kpi"><span>Balance proyectado</span><strong>{money(projected)}</strong></div></section>
  <div className="card toolbar"><form className="filters"><Hidden y={year} m={month}/><input name="q" placeholder="Buscar concepto" defaultValue={q}/><select name="category" defaultValue={cat}><option value="">Todas las categorías</option>{allCats.map(c=><option key={c.id}>{c.name}</option>)}</select><select name="status" defaultValue={status}><option value="">Todos</option><option value="pagado">Pagado</option><option value="pendiente">Pendiente</option></select><button>Filtrar</button></form><div className="export-group"><a className="export-btn" href={`/api/export?year=${year}&month=${month}`}>CSV</a><a className="export-btn" href={`/api/export/excel?year=${year}&month=${month}`}>Excel</a><a className="export-btn" href={`/api/export/pdf?year=${year}&month=${month}`}>PDF</a></div></div>
  <section className="grid cols"><div className="card"><h2>Nuevo ingreso</h2><form action={addIncome} className="form"><Hidden y={year} m={month}/><input name="concept" placeholder="Concepto" required/><select name="source"><option value="sueldo">Sueldo</option><option value="comision">Comisión</option><option value="bonus">Bonus</option><option value="extra">Extra</option></select><input name="amount" type="number" step=".01" placeholder="Monto" required/><input name="occurred_on" type="date" defaultValue={selectedDate}/><select name="status"><option value="pagado">Pagado</option><option value="pendiente">Pendiente</option></select><button>Agregar</button></form></div>
  <div className="card"><h2>Nuevo gasto</h2><form action={addExpense} className="form"><Hidden y={year} m={month}/><input name="concept" placeholder="Concepto" required/><select name="category">{allCats.map(c=><option key={c.id}>{c.name}</option>)}</select><input name="amount" type="number" step=".01" placeholder="Monto" required/><input name="occurred_on" type="date" defaultValue={selectedDate}/><select name="status"><option value="pagado">Pagado</option><option value="pendiente">Pendiente</option></select><button>Agregar</button></form></div></section>
  <section className="grid cols"><div className="card"><h2>Ingresos del período</h2>{inc.rows.map(r=><details className="movement" key={r.id}><summary>{dv(r.occurred_on)} · {r.concept} · <b>{money(r.amount)}</b> · {r.status}</summary><form action={updateIncome} className="edit-row"><Hidden y={year} m={month}/><input type="hidden" name="id" value={r.id}/><input name="occurred_on" type="date" defaultValue={dv(r.occurred_on)}/><input name="concept" defaultValue={r.concept}/><select name="source" defaultValue={r.source}><option value="sueldo">Sueldo</option><option value="comision">Comisión</option><option value="bonus">Bonus</option><option value="extra">Extra</option></select><input name="amount" type="number" step=".01" defaultValue={Number(r.amount)}/><select name="status" defaultValue={r.status}><option value="pagado">Pagado</option><option value="pendiente">Pendiente</option></select><button>Guardar</button></form><form action={deleteIncome}><Hidden y={year} m={month}/><input type="hidden" name="id" value={r.id}/><button className="delete-btn">Eliminar</button></form></details>)}</div>
  <div className="card"><h2>Gastos del período</h2>{exp.rows.map(r=><details className="movement" key={r.id}><summary>{dv(r.occurred_on)} · {r.concept} · <b>{money(r.amount)}</b> · {r.status}</summary><form action={updateExpense} className="edit-row"><Hidden y={year} m={month}/><input type="hidden" name="id" value={r.id}/><input name="occurred_on" type="date" defaultValue={dv(r.occurred_on)}/><input name="concept" defaultValue={r.concept}/><select name="category" defaultValue={r.category}>{allCats.map(c=><option key={c.id}>{c.name}</option>)}</select><input name="amount" type="number" step=".01" defaultValue={Number(r.amount)}/><select name="status" defaultValue={r.status}><option value="pagado">Pagado</option><option value="pendiente">Pendiente</option></select><button>Guardar</button></form><form action={deleteExpense}><Hidden y={year} m={month}/><input type="hidden" name="id" value={r.id}/><button className="delete-btn">Eliminar</button></form></details>)}</div></section>
  <section className="grid cols"><div className="card"><h2>Presupuesto por categoría</h2>{allCats.map(c=>{const b=budgets.rows.find(x=>Number(x.category_id)===Number(c.id)),spent=spendBy[c.name]||0,limit=Number(b?.amount||0),p=limit?spent/limit*100:0;return <div className="budget" key={c.id}><div><b>{c.name}</b> {money(spent)} / {limit?money(limit):'Sin límite'} {limit&&<span>{p.toFixed(0)}%</span>}</div>{limit>0&&<div className="bar"><span style={{width:`${Math.min(p,100)}%`}}/></div>}<form action={setBudget} className="mini"><Hidden y={year} m={month}/><input type="hidden" name="category_id" value={c.id}/><input name="amount" type="number" step=".01" defaultValue={limit||''} placeholder="Presupuesto"/><button>Guardar</button></form></div>})}</div>
  <div className="card"><h2>Categorías</h2><form action={addCategory} className="mini"><Hidden y={year} m={month}/><input name="name" placeholder="Nueva categoría"/><button>Agregar</button></form>{cats.rows.map(c=><form action={toggleCategory} className="category-row" key={c.id}><Hidden y={year} m={month}/><input type="hidden" name="id" value={c.id}/><span>{c.name}</span><button>{c.active?'Desactivar':'Activar'}</button></form>)}</div></section>
  <section className="grid cols"><div className="card"><h2>Recurrentes</h2><form action={addRecurring} className="stack"><Hidden y={year} m={month}/><select name="kind"><option value="expense">Gasto</option><option value="income">Ingreso</option></select><input name="concept" placeholder="Concepto"/><select name="category"><option value="">— Categoría —</option>{allCats.map(c=><option key={c.id}>{c.name}</option>)}</select><select name="source"><option value="">— Origen —</option><option value="sueldo">Sueldo</option><option value="comision">Comisión</option><option value="bonus">Bonus</option><option value="extra">Extra</option></select><input name="amount" type="number" step=".01" placeholder="Monto"/><input name="day_of_month" type="number" min="1" max="28" placeholder="Día"/><select name="status"><option value="pendiente">Pendiente</option><option value="pagado">Pagado</option></select><button>Crear recurrente</button></form>{recurring.rows.map(r=><form action={deleteRecurring} className="category-row" key={r.id}><Hidden y={year} m={month}/><input type="hidden" name="id" value={r.id}/><span>{r.concept} · día {r.day_of_month} · {money(r.amount)}</span><button>Eliminar</button></form>)}</div>
  <div className="card"><h2>Metas de ahorro</h2><form action={addGoal} className="stack"><Hidden y={year} m={month}/><input name="name" placeholder="Meta"/><input name="target_amount" type="number" step=".01" placeholder="Objetivo"/><input name="current_amount" type="number" step=".01" placeholder="Ahorrado"/><input name="target_date" type="date"/><button>Crear meta</button></form>{goals.rows.map(g=><div className="goal" key={g.id}><b>{g.name}</b><div>{money(g.current_amount)} / {money(g.target_amount)} · {(Number(g.current_amount)/Number(g.target_amount)*100).toFixed(0)}%</div><div className="bar"><span style={{width:`${Math.min(100,Number(g.current_amount)/Number(g.target_amount)*100)}%`}}/></div><form action={updateGoal} className="mini"><Hidden y={year} m={month}/><input type="hidden" name="id" value={g.id}/><input name="current_amount" type="number" step=".01" defaultValue={Number(g.current_amount)}/><input name="target_amount" type="hidden" value={Number(g.target_amount)}/><input name="target_date" type="hidden" value={g.target_date?dv(g.target_date):''}/><button>Actualizar</button></form><form action={deleteGoal}><Hidden y={year} m={month}/><input type="hidden" name="id" value={g.id}/><button className="delete-btn">Eliminar</button></form></div>)}</div></section>
  <section className="card"><h2>Evolución anual {year}</h2><div className="month-grid">{monthSeries.rows.map((r,i)=><div className="month-col" key={r.m}><b>{months[i]}</b><small className="positive">{money(r.income)}</small><small className="negative">{money(r.expense)}</small></div>)}</div><p>Ingresos anuales: <b>{money(annual.rows[0].income)}</b> · Gastos: <b>{money(annual.rows[0].expense)}</b> · Ahorro: <b>{money(Number(annual.rows[0].income)-Number(annual.rows[0].expense))}</b></p></section>
  <section className="card"><h2>Importar CSV</h2><p className="muted">Columnas: tipo,fecha,concepto,categoria,origen,monto,estado</p><form action={importCsv} className="stack"><Hidden y={year} m={month}/><textarea name="csv" rows="6" placeholder="tipo,fecha,concepto,categoria,origen,monto,estado&#10;gasto,2026-09-10,Supermercado,Alimentación,,2500,pagado"/><button>Importar</button></form></section>
 </main>
}