import { pool } from '../lib/db';
import ThemeToggle from './ThemeToggle';
import Movements from './Movements';
import QuickAdd from './QuickAdd';
import SectionModal from './SectionModal';
import AdvancedFinance from './AdvancedFinance';
import ImportPreview from './ImportPreview';
import StartHere from './StartHere';
import {logout} from './auth-actions';
import {addIncome,addExpense,updateIncome,updateExpense,deleteIncome,deleteExpense,setBudget,addCategory,toggleCategory,addRecurring,updateRecurring,toggleRecurring,deleteRecurring,setMonthlyBudget,addGoal,updateGoal,deleteGoal,importCsv,addExpenseAdvanced} from './actions';
const money=n=>new Intl.NumberFormat('es-UY',{style:'currency',currency:'UYU',maximumFractionDigits:0}).format(Number(n||0));
const dv=v=>typeof v==='string'?v.slice(0,10):new Date(v).toISOString().slice(0,10);
const months=['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'];
const Hidden=({y,m})=><><input type="hidden" name="view_year" value={y}/><input type="hidden" name="view_month" value={m}/></>;

async function materializeRecurring(year,month,userId){
 const key=`${year}-${String(month).padStart(2,'0')}`, first=`${key}-01`, items=(await pool.query('SELECT * FROM recurring_items WHERE user_id=$2 AND active=true AND (start_date IS NULL OR start_date <= $1) AND (end_date IS NULL OR end_date >= $1)',[first,userId])).rows;
 const days=new Date(year,month,0).getDate();
 for(const r of items){const date=`${key}-${String(Math.min(r.day_of_month,days)).padStart(2,'0')}`;
  if(r.kind==='income') await pool.query(`INSERT INTO income(concept,source,amount,occurred_on,status,recurring_id,period_key,user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(recurring_id,period_key) WHERE recurring_id IS NOT NULL DO NOTHING`,[r.concept,r.source||'extra',r.amount,date,r.status,r.id,key,userId]);
  else await pool.query(`INSERT INTO expense(concept,category,amount,occurred_on,status,recurring_id,period_key,user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(recurring_id,period_key) WHERE recurring_id IS NOT NULL DO NOTHING`,[r.concept,r.category||'Otros',r.amount,date,r.status,r.id,key,userId]);
 }
}

export default async function Dashboard({params,user}){
 const now=new Date(),year=Number(params?.year||now.getFullYear()),month=Number(params?.month||now.getMonth()+1);
 await materializeRecurring(year,month,user.id);
 const from=`${year}-${String(month).padStart(2,'0')}-01`,to=new Date(Date.UTC(year,month,1)).toISOString().slice(0,10);
 const prevDate=new Date(Date.UTC(year,month-2,1)),pf=prevDate.toISOString().slice(0,10),pt=from;
 const q=String(params?.q||'').trim(),cat=String(params?.category||''),status=String(params?.status||'');
 const safeQuery=async(sql,args=[])=>{try{return await pool.query(sql,args)}catch(e){console.error('Optional finance query failed:',e?.message);return {rows:[]}}};
 const accountBalancesQuery=(async()=>{try{return await pool.query(`SELECT a.*, a.opening_balance
    + COALESCE((SELECT SUM(i.amount) FROM income i WHERE i.deleted_at IS NULL AND i.status='pagado' AND i.account_id=a.id),0)
    - COALESCE((SELECT SUM(e.amount) FROM expense e WHERE e.deleted_at IS NULL AND e.status='pagado' AND e.account_id=a.id AND e.credit_card_id IS NULL),0)
    - COALESCE((SELECT SUM(cp.amount) FROM card_payments cp WHERE cp.account_id=a.id),0)
    + COALESCE((SELECT SUM(t.amount) FROM transfers t WHERE t.to_account_id=a.id),0)
    - COALESCE((SELECT SUM(t.amount) FROM transfers t WHERE t.from_account_id=a.id),0) AS current_balance
   FROM accounts a WHERE a.user_id=$1 AND a.active=true ORDER BY a.name`,[user.id])}catch(e){console.error('Card payments unavailable in balances:',e?.message);return pool.query(`SELECT a.*, a.opening_balance
    + COALESCE((SELECT SUM(i.amount) FROM income i WHERE i.deleted_at IS NULL AND i.status='pagado' AND i.account_id=a.id),0)
    - COALESCE((SELECT SUM(e.amount) FROM expense e WHERE e.deleted_at IS NULL AND e.status='pagado' AND e.account_id=a.id AND e.credit_card_id IS NULL),0)
    + COALESCE((SELECT SUM(t.amount) FROM transfers t WHERE t.to_account_id=a.id),0)
    - COALESCE((SELECT SUM(t.amount) FROM transfers t WHERE t.from_account_id=a.id),0) AS current_balance
   FROM accounts a WHERE a.user_id=$1 AND a.active=true ORDER BY a.name`,[user.id])}})();
 const [inc,exp,prevInc,prevExp,cats,budgets,monthlyBudget,recurring,goals,annual,monthSeries,accounts,cards,debts,tags,closure,accountBalances,cardStatements,debtInstallments,debtPaymentStats,cardPayments,cardMonthItems,cardPaymentHistory,futureCommitments]=await Promise.all([
  pool.query(`SELECT * FROM income WHERE user_id=$5 AND deleted_at IS NULL AND occurred_on >= $1 AND occurred_on < $2 AND ($3='' OR concept ILIKE '%'||$3||'%') AND ($4='' OR status=$4) ORDER BY occurred_on DESC,id DESC`,[from,to,q,status,user.id]),
  pool.query(`SELECT * FROM expense WHERE user_id=$6 AND deleted_at IS NULL AND occurred_on >= $1 AND occurred_on < $2 AND ($3='' OR concept ILIKE '%'||$3||'%') AND ($4='' OR category=$4) AND ($5='' OR status=$5) ORDER BY occurred_on DESC,id DESC`,[from,to,q,cat,status,user.id]),
  pool.query('SELECT COALESCE(SUM(amount),0) total FROM income WHERE user_id=$3 AND deleted_at IS NULL AND occurred_on >= $1 AND occurred_on < $2',[pf,pt,user.id]),
  pool.query('SELECT COALESCE(SUM(amount),0) total FROM expense WHERE user_id=$3 AND deleted_at IS NULL AND occurred_on >= $1 AND occurred_on < $2',[pf,pt,user.id]),
  pool.query('SELECT * FROM categories WHERE user_id=$1 ORDER BY sort_order,name',[user.id]),
  pool.query('SELECT b.*,c.name category FROM budgets b JOIN categories c ON c.id=b.category_id WHERE b.user_id=$3 AND year=$1 AND month=$2',[year,month,user.id]),
  pool.query('SELECT amount FROM monthly_budgets WHERE user_id=$3 AND year=$1 AND month=$2',[year,month,user.id]),
  pool.query('SELECT * FROM recurring_items WHERE user_id=$1 ORDER BY kind,concept',[user.id]),
  pool.query('SELECT * FROM savings_goals WHERE user_id=$1 ORDER BY id DESC',[user.id]),
  pool.query(`SELECT COALESCE((SELECT SUM(amount) FROM income WHERE user_id=$2 AND deleted_at IS NULL AND EXTRACT(YEAR FROM occurred_on)=$1),0) income,COALESCE((SELECT SUM(amount) FROM expense WHERE user_id=$2 AND deleted_at IS NULL AND EXTRACT(YEAR FROM occurred_on)=$1),0) expense`,[year,user.id]),
  pool.query(`WITH m AS(SELECT generate_series(1,12)m) SELECT m.m,COALESCE((SELECT SUM(amount) FROM income i WHERE i.user_id=$2 AND i.deleted_at IS NULL AND EXTRACT(YEAR FROM i.occurred_on)=$1 AND EXTRACT(MONTH FROM i.occurred_on)=m.m),0) income,COALESCE((SELECT SUM(amount) FROM expense e WHERE e.user_id=$2 AND e.deleted_at IS NULL AND EXTRACT(YEAR FROM e.occurred_on)=$1 AND EXTRACT(MONTH FROM e.occurred_on)=m.m),0) expense FROM m ORDER BY m.m`,[year,user.id]),
  pool.query('SELECT * FROM accounts WHERE user_id=$1 AND active=true ORDER BY name',[user.id]),
  pool.query('SELECT * FROM credit_cards WHERE user_id=$1 AND active=true ORDER BY name',[user.id]),
  pool.query('SELECT * FROM debts WHERE user_id=$1 ORDER BY status,name',[user.id]),
  pool.query('SELECT * FROM tags WHERE user_id=$1 ORDER BY name',[user.id]),
  pool.query('SELECT * FROM monthly_closures WHERE user_id=$3 AND year=$1 AND month=$2',[year,month,user.id]),
  accountBalancesQuery,
  pool.query(`SELECT c.id,c.name,c.closing_day,c.due_day,c.account_id,c.last_payment_date,
    COALESCE(SUM(CASE WHEN e.deleted_at IS NULL AND e.occurred_on >= $2 AND e.occurred_on < $3 THEN e.amount ELSE 0 END),0) total,
    COALESCE(SUM(CASE WHEN e.deleted_at IS NULL AND e.occurred_on >= $2 AND e.occurred_on < $3 AND e.status='pendiente' THEN e.amount ELSE 0 END),0) pending_total,
    COUNT(e.id) FILTER (WHERE e.deleted_at IS NULL AND e.occurred_on >= $2 AND e.occurred_on < $3) movements
   FROM credit_cards c LEFT JOIN expense e ON e.credit_card_id=c.id AND e.user_id=c.user_id
   WHERE c.user_id=$1 AND c.active=true GROUP BY c.id ORDER BY c.name`,[user.id,from,to]),
  pool.query(`SELECT di.*,d.name debt_name FROM debt_installments di JOIN debts d ON d.id=di.debt_id WHERE d.user_id=$1 AND di.due_date >= $2 AND di.due_date < $3 ORDER BY di.due_date,di.installment_number`,[user.id,from,to]),
  pool.query(`SELECT d.id debt_id,COUNT(di.id) FILTER (WHERE di.status='paid')::int paid_count,COALESCE(SUM(di.amount) FILTER (WHERE di.status='paid'),0) paid_total,COUNT(di.id)::int total_count FROM debts d LEFT JOIN debt_installments di ON di.debt_id=d.id WHERE d.user_id=$1 GROUP BY d.id`,[user.id]),
  safeQuery('SELECT * FROM card_payments WHERE user_id=$1 AND year=$2 AND month=$3',[user.id,year,month]),
  pool.query(`SELECT e.id,e.concept,e.amount,e.occurred_on,e.status,e.credit_card_id,e.installment_number,e.installment_total,c.name card_name FROM expense e JOIN credit_cards c ON c.id=e.credit_card_id WHERE e.user_id=$1 AND e.deleted_at IS NULL AND e.occurred_on >= $2 AND e.occurred_on < $3 ORDER BY c.name,e.occurred_on,e.id`,[user.id,from,to]),
  safeQuery(`SELECT cp.*,c.name card_name FROM card_payments cp JOIN credit_cards c ON c.id=cp.credit_card_id WHERE cp.user_id=$1 ORDER BY cp.year DESC,cp.month DESC LIMIT 36`,[user.id]),
  safeQuery(`SELECT occurred_on date,concept label,amount,'expense' kind FROM expense WHERE user_id=$1 AND deleted_at IS NULL AND status='pendiente' AND occurred_on >= $2::date AND occurred_on < ($2::date + interval '3 months') UNION ALL SELECT due_date date,d.name||' · cuota '||di.installment_number label,di.amount,'debt' kind FROM debt_installments di JOIN debts d ON d.id=di.debt_id WHERE d.user_id=$1 AND di.status='pending' AND di.due_date >= $2::date AND di.due_date < ($2::date + interval '3 months') ORDER BY date`,[user.id,from])
 ]);
 const allCats=cats.rows.filter(x=>x.active),income=inc.rows.reduce((a,x)=>a+Number(x.amount),0),expense=exp.rows.reduce((a,x)=>a+Number(x.amount),0);
 const paidIncome=inc.rows.filter(x=>x.status==='pagado').reduce((a,x)=>a+Number(x.amount),0),paidExpense=exp.rows.filter(x=>x.status==='pagado').reduce((a,x)=>a+Number(x.amount),0);
 const pendingIncome=income-paidIncome,pendingExpense=expense-paidExpense,projected=paidIncome+pendingIncome-paidExpense-pendingExpense;
 const pi=Number(prevInc.rows[0].total),pe=Number(prevExp.rows[0].total),pct=(a,b)=>b?((a-b)/b*100):0;
 const spendBy=Object.fromEntries(allCats.map(c=>[c.name,exp.rows.filter(x=>x.category===c.name).reduce((a,x)=>a+Number(x.amount),0)]));
 const savingsRate=income>0?(income-expense)/income*100:0;
 const topCategory=Object.entries(spendBy).sort((a,b)=>b[1]-a[1])[0]||['Sin gastos',0];
 const budgetAlerts=budgets.rows.map(b=>({category:b.category,limit:Number(b.amount),spent:Number(spendBy[b.category]||0)})).filter(x=>x.limit>0&&x.spent/x.limit>=.8).sort((a,b)=>(b.spent/b.limit)-(a.spent/a.limit));
 const expenseChange=pct(expense,pe);
 const analysisItems=[
  income===0?{tone:'warn',title:'Sin ingresos registrados',text:'No hay ingresos cargados para este período.'}:savingsRate>=20?{tone:'good',title:'Buen nivel de ahorro',text:`Estás conservando ${savingsRate.toFixed(1)}% de tus ingresos este mes.`}:savingsRate>=0?{tone:'warn',title:'Margen de ahorro bajo',text:`Tu ahorro del período es ${savingsRate.toFixed(1)}% de los ingresos.`}:{tone:'bad',title:'Gastas más de lo que ingresa',text:`El déficit del período es ${money(Math.abs(income-expense))}.`},
  {tone:expenseChange>10?'bad':expenseChange>0?'warn':'good',title:'Gastos vs. mes anterior',text:pe?`${expenseChange>=0?'Subieron':'Bajaron'} ${Math.abs(expenseChange).toFixed(1)}% respecto al mes anterior.`:'No hay suficiente historial anterior para comparar.'},
  {tone:'info',title:'Mayor categoría de gasto',text:topCategory[1]>0?`${topCategory[0]} concentra ${money(topCategory[1])} del gasto del período.`:'Todavía no hay gastos registrados.'},
  pendingExpense>0?{tone:'warn',title:'Pagos pendientes',text:`Tienes ${money(pendingExpense)} marcado como pendiente de pago.`}:{tone:'good',title:'Sin pagos pendientes',text:'No tienes gastos pendientes en el período.'}
 ];
 const selectedDate=year===now.getFullYear()&&month===now.getMonth()+1?now.toISOString().slice(0,10):from;
 const daysLeft=Math.max(1,new Date(year,month,0).getDate()-now.getDate()+1),daily=expense/Math.max(1,now.getDate()),forecastExpense=expense+daily*daysLeft;
 const recurringMonthly=recurring.rows.filter(r=>r.active&&r.kind==='expense').reduce((a,r)=>a+Number(r.amount),0),debtMonthly=debts.rows.filter(d=>d.status==='active').reduce((a,d)=>a+Number(d.installment_amount||0),0),base=income-expense;
 const accountTotal=accountBalances.rows.reduce((a,x)=>a+Number(x.current_balance||0),0),cardPending=cardStatements.rows.reduce((a,x)=>a+Number(x.pending_total||0),0),debtDueMonth=debtInstallments.rows.filter(x=>x.status==='pending').reduce((a,x)=>a+Number(x.amount),0),committedNow=pendingExpense+debtDueMonth,freeMoney=accountTotal+pendingIncome-committedNow;
 const commitmentMonths=[0,1,2].map(offset=>{const d=new Date(Date.UTC(year,month-1+offset,1)),y=d.getUTCFullYear(),m=d.getUTCMonth()+1,total=futureCommitments.rows.filter(x=>{const z=dv(x.date);return Number(z.slice(0,4))===y&&Number(z.slice(5,7))===m}).reduce((a,x)=>a+Number(x.amount),0);return {year:y,month:m,total}});
 const forecast={d30:accountTotal+pendingIncome-commitmentMonths[0].total,d60:accountTotal+pendingIncome-commitmentMonths.slice(0,2).reduce((a,x)=>a+x.total,0),d90:accountTotal+pendingIncome-commitmentMonths.reduce((a,x)=>a+x.total,0)};
 const pressure=income>0?committedNow/income:committedNow>0?1:0,health=freeMoney<0||pressure>.9?{tone:'bad',label:'Riesgo',text:`Tus compromisos superan el margen disponible. Faltan ${money(Math.abs(Math.min(0,freeMoney)))} para cubrir el escenario actual.`}:pressure>.65||pendingExpense>paidIncome*.5?{tone:'warn',label:'Atención',text:`Tienes ${money(committedNow)} comprometidos. Conviene cuidar nuevas compras hasta cubrir los pendientes.`}:{tone:'good',label:'Bien',text:`Después de pendientes y compromisos estimados quedarían ${money(Math.max(0,freeMoney))} libres.`};
 const installmentUpcoming=debtInstallments.rows.filter(x=>x.status==='pending').map(x=>({date:dv(x.due_date),label:`${x.debt_name} · cuota ${x.installment_number}`,amount:Number(x.amount)}));
 const upcoming=[...recurring.rows.filter(r=>r.active&&r.kind==='expense').map(r=>({date:`${year}-${String(month).padStart(2,'0')}-${String(Math.min(r.day_of_month,28)).padStart(2,'0')}`,label:r.concept,amount:Number(r.amount)})),...installmentUpcoming,...debts.rows.filter(d=>d.status==='active'&&d.due_date&&!debtInstallments.rows.some(x=>Number(x.debt_id)===Number(d.id))).map(d=>({date:dv(d.due_date),label:`Deuda: ${d.name}`,amount:Number(d.installment_amount||d.current_balance)}))].sort((a,b)=>a.date.localeCompare(b.date)).slice(0,20);
 return <main className="wrap">
  <div className="hero"><div><div className="brand-title"><img src="/logo.png" alt="KNJ"/><div><div className="muted">FINANZAS PERSONALES</div></div></div><div className="period-badge">{months[month-1]} {year}</div></div>
   <div className="hero-actions"><span className="user-chip">{user.email}</span>{user.role==='admin'&&<a className="export-btn" href="/admin">Admin</a>}<form action={logout}><button className="secondary-btn">Salir</button></form><ThemeToggle/><form className="filters"><select name="month" defaultValue={month}>{months.map((x,i)=><option value={i+1} key={x}>{x}</option>)}</select><select name="year" defaultValue={year}>{Array.from({length:11},(_,i)=>year-5+i).map(y=><option key={y}>{y}</option>)}</select><button>Ver período</button></form></div>
  </div>
  <nav className="main-nav"><a className="active" href="#resumen">Resumen</a><a href="#movimientos">Movimientos</a><a href="#finanzas">Mi dinero</a><a href="#organizar">Organizar</a><a href="#herramientas">Herramientas</a></nav>
  <section id="resumen" className="platform-zone zone-summary"><div className="zone-label"><span>01</span><div><b>Resumen</b><small>Tu situación del mes</small></div></div><div className="dashboard-layout"><div className="dashboard-primary"><StartHere hasAccounts={accountBalances.rows.length>1} hasIncome={inc.rows.length>0} hasExpense={exp.rows.length>0} hasCommitments={cards.rows.length>0||debts.rows.length>0||recurring.rows.length>0}/>
  <section className="summary-dashboard"><div className="summary-balance card"><div><span className="eyebrow">SITUACIÓN DEL MES</span><small>Balance total previsto</small><strong className={income-expense>=0?'positive':'negative'}>{money(income-expense)}</strong></div><div className="summary-balance-side"><span><small>Balance real hoy</small><b>{money(paidIncome-paidExpense)}</b></span><span><small>Balance proyectado</small><b>{money(projected)}</b></span></div></div><div className="summary-flow"><div className="summary-group income-summary"><div className="summary-group-head"><div><span className="summary-icon">↓</span><div><small>INGRESOS DEL MES</small><strong>{money(income)}</strong></div></div><em>{pct(income,pi).toFixed(1)}% vs anterior</em></div><div className="summary-split"><div className="received"><small>✓ Ya recibido</small><b>{money(paidIncome)}</b><span>{income>0?(paidIncome/income*100).toFixed(0):0}%</span></div><div className="to-receive"><small>◷ Por recibir</small><b>{money(pendingIncome)}</b><span>{income>0?(pendingIncome/income*100).toFixed(0):0}%</span></div></div><div className="summary-progress"><i style={{width:`${income>0?Math.min(100,paidIncome/income*100):0}%`}}/></div></div><div className="summary-group expense-summary"><div className="summary-group-head"><div><span className="summary-icon">↑</span><div><small>GASTOS DEL MES</small><strong>{money(expense)}</strong></div></div><em>{pct(expense,pe).toFixed(1)}% vs anterior</em></div><div className="summary-split"><div className="paid"><small>✓ Ya pagado</small><b>{money(paidExpense)}</b><span>{expense>0?(paidExpense/expense*100).toFixed(0):0}%</span></div><div className="pending"><small>◷ Por pagar</small><b>{money(pendingExpense)}</b><span>{expense>0?(pendingExpense/expense*100).toFixed(0):0}%</span></div></div><div className="summary-progress"><i style={{width:`${expense>0?Math.min(100,paidExpense/expense*100):0}%`}}/></div></div></div></section></div><aside className="dashboard-side"><section className="financial-pulse"><div className={`health-card ${health.tone}`}><div><span className="eyebrow">SEMÁFORO FINANCIERO</span><strong>{health.label}</strong></div><p>{health.text}</p></div><div className="commitment-strip"><span><small>Disponible en cuentas</small><b>{money(accountTotal)}</b></span><span><small>Comprometido ahora</small><b>{money(committedNow)}</b></span><span><small>Dinero libre estimado</small><b className={freeMoney>=0?'positive':'negative'}>{money(freeMoney)}</b></span><span><small>Tarjetas por pagar</small><b>{money(cardPending)}</b></span></div><div className="commitment-horizon">{commitmentMonths.map((x,i)=><div key={i}><small>{i===0?'Este mes':i===1?'Próximo mes':'En 2 meses'}</small><b>{money(x.total)}</b><i style={{width:`${Math.min(100,x.total/Math.max(1,...commitmentMonths.map(z=>z.total))*100)}%`}}/></div>)}</div></section></aside></div>
  <div className="insights-layout"><section className="analysis-section"><div className="section-head"><div><span className="eyebrow">ANÁLISIS DEL MES</span><h2>Lectura rápida de tus finanzas</h2></div></div><div className="analysis-grid">{analysisItems.map((a,i)=><div className={`analysis-card ${a.tone}`} key={i}><b>{a.title}</b><p>{a.text}</p></div>)}</div>{budgetAlerts.length>0&&<div className="budget-alert"><b>Atención a presupuestos</b><span>{budgetAlerts.slice(0,3).map(x=>`${x.category}: ${(x.spent/x.limit*100).toFixed(0)}%`).join(' · ')}</span></div>}</section>
  {expense>0&&<section className="category-visual"><div className="card"><div className="section-head"><div><span className="eyebrow">DISTRIBUCIÓN</span><h2>¿Dónde se va el dinero?</h2></div></div><div className="category-bars">{Object.entries(spendBy).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([name,value])=><div className="category-bar" key={name}><div><b>{name}</b><span>{money(value)} · {(value/expense*100).toFixed(0)}%</span></div><div className="bar"><span style={{width:`${Math.min(100,value/expense*100)}%`}}/></div></div>)}</div></div></section>}</div>
  </section>
  <section className="platform-zone zone-movements"><div className="zone-label"><span>02</span><div><b>Movimientos</b><small>Registra, busca y revisa operaciones</small></div></div><div className="card toolbar"><form className="filters"><Hidden y={year} m={month}/><input name="q" placeholder="Buscar concepto" defaultValue={q}/><select name="category" defaultValue={cat}><option value="">Todas las categorías</option>{allCats.map(c=><option key={c.id}>{c.name}</option>)}</select><select name="status" defaultValue={status}><option value="">Todos</option><option value="pagado">Pagado</option><option value="pendiente">Pendiente</option></select><button>Filtrar</button></form><div className="export-group"><a className="export-btn" href={`/api/export?year=${year}&month=${month}`}>CSV</a><a className="export-btn" href={`/api/export/excel?year=${year}&month=${month}`}>Excel</a><a className="export-btn" href={`/api/export/pdf?year=${year}&month=${month}`}>PDF</a></div></div>

  <QuickAdd categories={allCats} accounts={accounts.rows} cards={cards.rows} year={year} month={month} selectedDate={selectedDate} advancedAction={addExpenseAdvanced}/>
  <section id="movimientos" className="section-block"><div className="section-head"><div><span className="eyebrow">MOVIMIENTOS</span><h2>Todos los movimientos · {months[month-1]} {year}</h2></div><span className="muted">Edita, duplica o elimina sin salir de la lista</span></div><Movements income={inc.rows} expenses={exp.rows} debtInstallments={debtInstallments.rows} categories={allCats} accounts={accounts.rows} cards={cards.rows} year={year} month={month}/></section></section>
  <section id="organizar" className="workspace-group platform-zone zone-organize"><div className="zone-label"><span>03</span><div><b>Organizar</b><small>Presupuestos, automatizaciones y metas</small></div></div><div className="workspace-heading"><span className="eyebrow">ORGANIZAR</span><h2>Presupuestos, automatizaciones y metas</h2><p className="muted">Estas opciones son de configuración. Ábrelas solo cuando necesites hacer cambios.</p></div>
  <section id="presupuestos" className="section-block compact-section"><div className="section-head"><div><span className="eyebrow">CONTROL</span><h2>Presupuestos y categorías</h2></div></div>
   <div className="card monthly-budget"><div><span className="eyebrow">LÍMITE GENERAL</span><h3>Presupuesto mensual</h3><p className="muted">Gastado {money(expense)} · {monthlyBudget.rows[0]?money(Math.max(0,Number(monthlyBudget.rows[0].amount)-expense))+' disponible':'Define tu límite del mes'}</p></div><form action={setMonthlyBudget} className="mini"><Hidden y={year} m={month}/><input name="amount" type="number" step=".01" min="0" placeholder="Límite mensual" required defaultValue={monthlyBudget.rows[0]?Number(monthlyBudget.rows[0].amount):''}/><button>Guardar</button></form></div>
   <div className="section-modal-grid">
    <SectionModal eyebrow="LÍMITES" title="Presupuesto por categoría" wide>{allCats.map(c=>{const b=budgets.rows.find(x=>Number(x.category_id)===Number(c.id)),spent=spendBy[c.name]||0,limit=Number(b?.amount||0),p=limit?spent/limit*100:0;return <div className="budget" key={c.id}><div><b>{c.name}</b> {money(spent)} / {limit?money(limit):'Sin límite'} {limit&&<span>{p.toFixed(0)}%</span>}</div>{limit>0&&<div className="bar"><span style={{width:`${Math.min(p,100)}%`}}/></div>}<form action={setBudget} className="mini"><Hidden y={year} m={month}/><input type="hidden" name="category_id" value={c.id}/><input name="amount" type="number" step=".01" min="0" defaultValue={limit||''} placeholder="Presupuesto" required/><button>Guardar</button></form></div>})}</SectionModal>
    <SectionModal eyebrow="CONFIGURACIÓN" title="Categorías"><form action={addCategory} className="mini"><Hidden y={year} m={month}/><input name="name" placeholder="Nueva categoría" required/><button>Agregar</button></form>{cats.rows.map(c=><form action={toggleCategory} className="category-row" key={c.id}><Hidden y={year} m={month}/><input type="hidden" name="id" value={c.id}/><span>{c.name}</span><button>{c.active?'Desactivar':'Activar'}</button></form>)}</SectionModal>
   </div>
  </section>
  <section id="planificacion" className="section-block compact-section"><div className="section-head"><div><span className="eyebrow">PLANIFICACIÓN</span><h2>Recurrentes y metas</h2></div></div><div className="section-modal-grid">
   <SectionModal eyebrow="AUTOMÁTICO" title="Recurrentes" wide><form action={addRecurring} className="stack"><Hidden y={year} m={month}/><select name="kind"><option value="expense">Gasto</option><option value="income">Ingreso</option></select><input name="concept" placeholder="Concepto" required/><select name="category"><option value="">— Categoría —</option>{allCats.map(c=><option key={c.id}>{c.name}</option>)}</select><select name="source"><option value="">— Origen —</option><option value="sueldo">Sueldo</option><option value="comision">Comisión</option><option value="bonus">Bonus</option><option value="extra">Extra</option></select><input name="amount" type="number" step=".01" min="0.01" placeholder="Monto" required/><input name="day_of_month" type="number" min="1" max="28" placeholder="Día" required/><label><span className="muted">Desde</span><input name="start_date" type="date"/></label><label><span className="muted">Hasta</span><input name="end_date" type="date"/></label><select name="status"><option value="pendiente">Pendiente</option><option value="pagado">Pagado</option></select><button>Crear recurrente</button></form>{recurring.rows.map(r=><details className="recurring-row" key={r.id}><summary><span>{r.active?'●':'○'} {r.concept} · día {r.day_of_month} · {money(r.amount)}</span><b>{r.active?'Activo':'Pausado'}</b></summary><form action={updateRecurring} className="recurring-edit"><Hidden y={year} m={month}/><input type="hidden" name="id" value={r.id}/><input name="concept" defaultValue={r.concept} required/><input name="amount" type="number" step=".01" min="0.01" defaultValue={Number(r.amount)} required/><input name="day_of_month" type="number" min="1" max="28" defaultValue={r.day_of_month} required/><select name="status" defaultValue={r.status}><option value="pendiente">Pendiente</option><option value="pagado">Pagado</option></select><input name="start_date" type="date" defaultValue={r.start_date?dv(r.start_date):''}/><input name="end_date" type="date" defaultValue={r.end_date?dv(r.end_date):''}/><button>Guardar cambios</button></form><div className="recurring-actions"><form action={toggleRecurring}><Hidden y={year} m={month}/><input type="hidden" name="id" value={r.id}/><button>{r.active?'Pausar':'Reactivar'}</button></form><form action={deleteRecurring}><Hidden y={year} m={month}/><input type="hidden" name="id" value={r.id}/><button className="delete-btn">Eliminar</button></form></div></details>)}</SectionModal>
   <SectionModal eyebrow="AHORRO" title="Metas de ahorro"><form action={addGoal} className="stack"><Hidden y={year} m={month}/><input name="name" placeholder="Meta" required/><input name="target_amount" type="number" step=".01" min="0.01" placeholder="Objetivo" required/><input name="current_amount" type="number" step=".01" min="0" placeholder="Ahorrado" required/><input name="target_date" type="date"/><button>Crear meta</button></form>{goals.rows.map(g=><div className="goal" key={g.id}><b>{g.name}</b><div>{money(g.current_amount)} / {money(g.target_amount)} · {(Number(g.current_amount)/Number(g.target_amount)*100).toFixed(0)}%</div><div className="bar"><span style={{width:`${Math.min(100,Number(g.current_amount)/Number(g.target_amount)*100)}%`}}/></div><form action={updateGoal} className="mini"><Hidden y={year} m={month}/><input type="hidden" name="id" value={g.id}/><input name="current_amount" type="number" step=".01" min="0" defaultValue={Number(g.current_amount)} required/><input name="target_amount" type="hidden" value={Number(g.target_amount)}/><input name="target_date" type="hidden" value={g.target_date?dv(g.target_date):''}/><button>Actualizar</button></form><form action={deleteGoal}><Hidden y={year} m={month}/><input type="hidden" name="id" value={g.id}/><button className="delete-btn">Eliminar</button></form></div>)}</SectionModal>
  </div></section>
  </section>
  <section className="platform-zone zone-finance"><div className="zone-label"><span>04</span><div><b>Mi dinero</b><small>Cuentas, tarjetas, deudas y calendario</small></div></div><AdvancedFinance accounts={accountBalances.rows} cards={cardStatements.rows} debts={debts.rows} tags={tags.rows} upcoming={upcoming} year={year} month={month} selectedDate={selectedDate} forecast={forecast} closure={closure.rows[0]||null} debtInstallments={debtInstallments.rows} debtPaymentStats={debtPaymentStats.rows} cardPayments={cardPayments.rows} cardMonthItems={cardMonthItems.rows} cardPaymentHistory={cardPaymentHistory.rows} commitments={futureCommitments.rows}/></section><section className="platform-zone zone-tools"><div className="zone-label"><span>05</span><div><b>Herramientas</b><small>Historial, análisis y archivos</small></div></div><section id="anual" className="section-block compact-section"><div className="section-head"><div><span className="eyebrow">AÑO</span><h2>Resumen {year}</h2></div></div><SectionModal eyebrow="AÑO" title={`Ver resumen anual ${year}`} wide><h3>Evolución mensual</h3><div className="annual-chart">{monthSeries.rows.map((r,i)=>{const max=Math.max(...monthSeries.rows.flatMap(x=>[Number(x.income),Number(x.expense)]),1);return <div className="chart-month" key={r.m}><div className="chart-bars"><i className="income-bar" style={{height:`${Math.max(2,Number(r.income)/max*100)}%`}}/><i className="expense-bar" style={{height:`${Math.max(2,Number(r.expense)/max*100)}%`}}/></div><small>{months[i]}</small></div>})}</div><div className="chart-legend"><span>■ Ingresos</span><span>■ Gastos</span></div><h3>Detalle por mes</h3><div className="month-grid">{monthSeries.rows.map((r,i)=><div className="month-col" key={r.m}><b>{months[i]}</b><small className="positive">{money(r.income)}</small><small className="negative">{money(r.expense)}</small></div>)}</div><p>Ingresos anuales: <b>{money(annual.rows[0].income)}</b> · Gastos: <b>{money(annual.rows[0].expense)}</b> · Ahorro: <b>{money(Number(annual.rows[0].income)-Number(annual.rows[0].expense))}</b></p></SectionModal></section>
  <section id="herramientas" className="section-block compact-section"><SectionModal eyebrow="HERRAMIENTAS" title="Herramientas e importación"><h3>Importar CSV</h3><p className="muted">Columnas: tipo,fecha,concepto,categoria,origen,monto,estado</p><ImportPreview action={importCsv} year={year} month={month}/><h3>Respaldo completo</h3><p className="muted">Descarga todos tus datos, incluidos comprobantes, en un archivo JSON privado.</p><a className="export-btn" href="/api/export/backup">Descargar respaldo completo</a></SectionModal></section>
  </section>
</main>
}