'use client';
import {useState,useTransition} from 'react';
import {updateIncome,updateExpense,deleteIncome,deleteExpense,restoreMovement,duplicateMovement,setDebtInstallmentStatus,setMovementStatus} from './actions';
import SafeForm from './SafeForm';
const money=n=>new Intl.NumberFormat('es-UY',{style:'currency',currency:'UYU',maximumFractionDigits:0}).format(Number(n||0));
const dateUY=v=>{const raw=String(v||'').trim(),days=['dom','lun','mar','mié','jue','vie','sáb'],months=['ene','feb','mar','abr','may','jun','jul','ago','sep','oct','nov','dic'];let y,m,d;const iso=raw.match(/^(\d{4})-(\d{2})-(\d{2})/);if(iso){y=Number(iso[1]);m=Number(iso[2]);d=Number(iso[3])}else{const parsed=new Date(raw);if(Number.isNaN(parsed.getTime()))return raw;y=parsed.getUTCFullYear();m=parsed.getUTCMonth()+1;d=parsed.getUTCDate()}const dt=new Date(Date.UTC(y,m-1,d));return days[dt.getUTCDay()]+' '+String(d).padStart(2,'0')+' '+months[m-1]};
export default function Movements({income,expenses,debtInstallments=[],categories,accounts=[],cards=[],year,month}){
 const debtRows=debtInstallments.map(x=>({id:x.id,kind:'debt',concept:x.debt_name+' · cuota '+x.installment_number,occurred_on:x.due_date,status:x.status==='paid'?'pagado':'pendiente',amount:x.amount,category:'Deuda'}));
 const rows=[...income.map(x=>({...x,kind:'income'})),...expenses.map(x=>({...x,kind:'expense'})),...debtRows].sort((a,b)=>String(b.occurred_on).localeCompare(String(a.occurred_on))||b.id-a.id);
 const [edit,setEdit]=useState(null),[deleted,setDeleted]=useState(null),[quickFilter,setQuickFilter]=useState('all'),[sort,setSort]=useState({key:'date',dir:'desc'}),[pending,start]=useTransition();
 const sortBy=key=>setSort(s=>({key,dir:s.key===key&&s.dir==='asc'?'desc':'asc'}));
 const arrow=key=>sort.key===key?(sort.dir==='asc'?' ↑':' ↓'):'';
 const quickRows=rows.filter(r=>quickFilter==='all'||quickFilter==='received'&&r.kind==='income'&&r.status==='pagado'||quickFilter==='to-receive'&&r.kind==='income'&&r.status==='pendiente'||quickFilter==='paid'&&r.kind!=='income'&&r.status==='pagado'||quickFilter==='to-pay'&&r.kind!=='income'&&r.status==='pendiente'||quickFilter==='cards'&&r.kind==='expense'&&r.credit_card_id||quickFilter==='installments'&&(r.kind==='debt'||r.installment_total));
 const visibleRows=[...quickRows].sort((a,b)=>{const value=r=>sort.key==='date'?String(r.occurred_on||''):sort.key==='concept'?String(r.concept||'').toLowerCase():sort.key==='type'?(r.kind==='income'?'Ingreso':r.kind==='debt'?'Cuota deuda':'Gasto'):sort.key==='category'?String(r.kind==='income'?r.source:r.category||'').toLowerCase():sort.key==='status'?String(r.status||''):Number(r.amount||0);const av=value(a),bv=value(b),cmp=sort.key==='amount'?av-bv:String(av).localeCompare(String(bv),'es',{numeric:true});return sort.dir==='asc'?cmp:-cmp});
 const del=r=>{if(!confirm(`¿Eliminar "${r.concept}"? Podrás deshacerlo.`))return;const fd=new FormData();fd.set('id',r.id);start(async()=>{await (r.kind==='income'?deleteIncome:deleteExpense)(fd);setDeleted(r);setEdit(null)})};
 const restore=()=>deleted&&start(async()=>{await restoreMovement(deleted.kind,deleted.id);setDeleted(null)});
 const duplicate=r=>start(async()=>{await duplicateMovement(r.kind,r.id)});
 const debtStatus=(r,next)=>start(async()=>{try{const fd=new FormData();fd.set('installment_id',String(r.id));fd.set('status',next);const result=await setDebtInstallmentStatus(fd);if(result?.ok===false)alert(result.error||'No se pudo cambiar el estado de la cuota')}catch(e){console.error(e);alert('No se pudo cambiar el estado de la cuota. Intenta nuevamente.')}});
 const movementStatus=(r,next)=>start(async()=>{try{const fd=new FormData();fd.set('id',String(r.id));fd.set('kind',r.kind);fd.set('status',next);const result=await setMovementStatus(fd);if(result?.ok===false)alert(result.error||'No se pudo cambiar el estado')}catch(e){console.error(e);alert('No se pudo cambiar el estado. Intenta nuevamente.')}});
 return <div className="card movements-card">
  <div className="movement-quick-filters">{[['all','Todos'],['received','Recibidos'],['to-receive','Por recibir'],['paid','Pagados'],['to-pay','Por pagar'],['cards','Tarjetas'],['installments','Cuotas']].map(([id,label])=><button type="button" key={id} className={quickFilter===id?'active':''} onClick={()=>setQuickFilter(id)}>{label}</button>)}</div>
  {deleted&&<div className="undo-toast"><span>Movimiento eliminado</span><button onClick={restore} disabled={pending}>Deshacer</button></div>}
  <div className="movement-table"><div className="movement-head sortable-head"><button type="button" onClick={()=>sortBy('date')}>Fecha{arrow('date')}</button><button type="button" onClick={()=>sortBy('concept')}>Concepto{arrow('concept')}</button><button type="button" onClick={()=>sortBy('type')}>Tipo{arrow('type')}</button><button type="button" onClick={()=>sortBy('category')}>Categoría / origen{arrow('category')}</button><button type="button" onClick={()=>sortBy('status')}>Estado{arrow('status')}</button><button type="button" onClick={()=>sortBy('amount')}>Monto{arrow('amount')}</button><span>Acciones</span></div>
  {visibleRows.length===0?<p className="empty">No hay movimientos para este filtro.</p>:visibleRows.map(r=><div className={`movement-row ${r.kind==='income'?(r.status==='pagado'?'is-received':'is-to-receive'):(r.status==='pagado'?'is-paid':'is-pending')}`} key={r.kind+r.id}><span className="movement-date">{dateUY(r.occurred_on)}</span><strong>{r.concept}<small className="movement-id">#{r.id}</small></strong><span><i className={`type-pill ${r.kind}`}>{r.kind==='income'?'Ingreso':r.kind==='debt'?'Cuota deuda':'Gasto'}</i></span><span>{r.kind==='income'?r.source:r.category}</span><span><i className={`status-pill ${r.kind==='income'?(r.status==='pagado'?'received':'to-receive'):(r.status==='pagado'?'paid':'pending')}`}>{r.kind==='income'?(r.status==='pagado'?'✓ Recibido':'◷ Por recibir'):(r.status==='pagado'?'✓ Pagado':'◷ Pendiente')}</i></span><b className={r.kind==='income'?'positive':'negative'}>{r.kind==='income'?'+':'−'} {money(r.amount)}</b><span className="row-actions">{r.kind==='debt'?<><button className="icon-btn state-paid" title="Marcar pagado" aria-label="Marcar pagado" onClick={()=>debtStatus(r,'paid')} disabled={pending||r.status==='pagado'}>✓</button><button className="icon-btn state-pending" title="Marcar pendiente" aria-label="Marcar pendiente" onClick={()=>debtStatus(r,'pending')} disabled={pending||r.status==='pendiente'}>◷</button></>:<><button className="icon-btn state-paid" title={r.kind==='income'?'Marcar recibido':'Marcar pagado'} aria-label={r.kind==='income'?'Marcar recibido':'Marcar pagado'} onClick={()=>movementStatus(r,'pagado')} disabled={pending||r.status==='pagado'}>✓</button><button className="icon-btn state-pending" title={r.kind==='income'?'Marcar por recibir':'Marcar pendiente'} aria-label={r.kind==='income'?'Marcar por recibir':'Marcar pendiente'} onClick={()=>movementStatus(r,'pendiente')} disabled={pending||r.status==='pendiente'}>◷</button><button className="icon-btn" title="Editar" aria-label="Editar" onClick={()=>setEdit(r)}>✎</button><button className="icon-btn" title="Duplicar" aria-label="Duplicar" onClick={()=>duplicate(r)} disabled={pending}>⧉</button><button className="icon-btn danger-link" title="Eliminar" aria-label="Eliminar" onClick={()=>del(r)} disabled={pending}>⌫</button></>}</span></div>)}</div>
  {edit&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setEdit(null)}><div className="modal-card"><div className="modal-title"><div><span className="eyebrow">EDITAR MOVIMIENTO</span><h3>{edit.concept}</h3></div><button className="modal-close" onClick={()=>setEdit(null)}>×</button></div><SafeForm action={edit.kind==='income'?updateIncome:updateExpense} className="modal-form" onSuccess={()=>setEdit(null)} successMessage="Cambios guardados"><input type="hidden" name="id" value={edit.id}/><input type="hidden" name="view_year" value={year}/><input type="hidden" name="view_month" value={month}/><label><span>Fecha</span><input name="occurred_on" type="date" defaultValue={String(edit.occurred_on).slice(0,10)} required/></label><label><span>Concepto</span><input name="concept" defaultValue={edit.concept} required/></label>{edit.kind==='income'?<label><span>Origen</span><select name="source" defaultValue={edit.source} required><option value="sueldo">Sueldo</option><option value="comision">Comisión</option><option value="bonus">Bonus</option><option value="extra">Extra</option></select></label>:<label><span>Categoría</span><select name="category" defaultValue={edit.category} required>{categories.map(c=><option key={c.id}>{c.name}</option>)}</select></label>}{edit.kind==='income'?<label><span>Cuenta</span><select name="account_id" defaultValue={edit.account_id||''}><option value="">Sin cuenta</option>{accounts.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label>:<label><span>Cuenta o tarjeta</span><select name="destination" defaultValue={edit.credit_card_id?`card:${edit.credit_card_id}`:edit.account_id?`account:${edit.account_id}`:''}><option value="">Sin asignar</option><optgroup label="Cuentas">{accounts.map(a=><option value={`account:${a.id}`} key={'a'+a.id}>{a.name}</option>)}</optgroup><optgroup label="Tarjetas">{cards.map(x=><option value={`card:${x.id}`} key={'c'+x.id}>{x.name}</option>)}</optgroup></select><small className="muted">Elige dónde se cobró o pagó este movimiento.</small></label>}<label><span>Monto</span><input name="amount" type="number" step=".01" min="0.01" defaultValue={Number(edit.amount)} required/></label><label><span>Estado</span><select name="status" defaultValue={edit.status} required><option value="pagado">Pagado</option><option value="pendiente">Pendiente</option></select></label><div className="modal-actions"><button type="button" className="secondary-btn" onClick={()=>setEdit(null)}>Cancelar</button><button disabled={pending}>{pending?'Guardando…':'Guardar cambios'}</button></div></SafeForm></div></div>}
 </div>
}