'use client';
import {useState,useTransition} from 'react';
import {updateIncome,updateExpense,deleteIncome,deleteExpense,restoreMovement,duplicateMovement} from './actions';
import SafeForm from './SafeForm';
const money=n=>new Intl.NumberFormat('es-UY',{style:'currency',currency:'UYU',maximumFractionDigits:0}).format(Number(n||0));
export default function Movements({income,expenses,categories,year,month}){
 const rows=[...income.map(x=>({...x,kind:'income'})),...expenses.map(x=>({...x,kind:'expense'}))].sort((a,b)=>String(b.occurred_on).localeCompare(String(a.occurred_on))||b.id-a.id);
 const [edit,setEdit]=useState(null),[deleted,setDeleted]=useState(null),[pending,start]=useTransition();
 const del=r=>{if(!confirm(`¿Eliminar "${r.concept}"? Podrás deshacerlo.`))return;const fd=new FormData();fd.set('id',r.id);start(async()=>{await (r.kind==='income'?deleteIncome:deleteExpense)(fd);setDeleted(r);setEdit(null)})};
 const restore=()=>deleted&&start(async()=>{await restoreMovement(deleted.kind,deleted.id);setDeleted(null)});
 const duplicate=r=>start(async()=>{await duplicateMovement(r.kind,r.id)});
 return <div className="card movements-card">
  {deleted&&<div className="undo-toast"><span>Movimiento eliminado</span><button onClick={restore} disabled={pending}>Deshacer</button></div>}
  <div className="movement-table"><div className="movement-head"><span>Fecha</span><span>Concepto</span><span>Tipo</span><span>Categoría / origen</span><span>Estado</span><span>Monto</span><span>Acciones</span></div>
  {rows.length===0?<p className="empty">No hay movimientos para estos filtros.</p>:rows.map(r=><div className="movement-row" key={r.kind+r.id}><span>{String(r.occurred_on).slice(0,10)}</span><strong>{r.concept}<small className="movement-id">#{r.id}</small></strong><span><i className={`type-pill ${r.kind}`}>{r.kind==='income'?'Ingreso':'Gasto'}</i></span><span>{r.kind==='income'?r.source:r.category}</span><span>{r.status}</span><b className={r.kind==='income'?'positive':'negative'}>{r.kind==='income'?'+':'−'} {money(r.amount)}</b><span className="row-actions"><button onClick={()=>setEdit(r)}>Editar</button><button onClick={()=>duplicate(r)} disabled={pending}>Duplicar</button><button className="danger-link" onClick={()=>del(r)} disabled={pending}>Eliminar</button></span></div>)}</div>
  {edit&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setEdit(null)}><div className="modal-card"><div className="modal-title"><div><span className="eyebrow">EDITAR MOVIMIENTO</span><h3>{edit.concept}</h3></div><button className="modal-close" onClick={()=>setEdit(null)}>×</button></div><SafeForm action={edit.kind==='income'?updateIncome:updateExpense} className="modal-form" onSuccess={()=>setEdit(null)} successMessage="Cambios guardados"><input type="hidden" name="id" value={edit.id}/><input type="hidden" name="view_year" value={year}/><input type="hidden" name="view_month" value={month}/><label><span>Fecha</span><input name="occurred_on" type="date" defaultValue={String(edit.occurred_on).slice(0,10)} required/></label><label><span>Concepto</span><input name="concept" defaultValue={edit.concept} required/></label>{edit.kind==='income'?<label><span>Origen</span><select name="source" defaultValue={edit.source} required><option value="sueldo">Sueldo</option><option value="comision">Comisión</option><option value="bonus">Bonus</option><option value="extra">Extra</option></select></label>:<label><span>Categoría</span><select name="category" defaultValue={edit.category} required>{categories.map(c=><option key={c.id}>{c.name}</option>)}</select></label>}<label><span>Monto</span><input name="amount" type="number" step=".01" min="0.01" defaultValue={Number(edit.amount)} required/></label><label><span>Estado</span><select name="status" defaultValue={edit.status} required><option value="pagado">Pagado</option><option value="pendiente">Pendiente</option></select></label><div className="modal-actions"><button type="button" className="secondary-btn" onClick={()=>setEdit(null)}>Cancelar</button><button disabled={pending}>{pending?'Guardando…':'Guardar cambios'}</button></div></SafeForm></div></div>}
 </div>
}