'use client';
import {useState,useTransition} from 'react';
import {addIncome,addExpense} from './actions';
import SafeForm from './SafeForm';
export default function QuickAdd({categories,year,month,selectedDate}){
 const fallbackDate=selectedDate||`${year}-${String(month).padStart(2,'0')}-01`;
 const [kind,setKind]=useState(null),[pending,start]=useTransition();
 return <><div className="quick-add-bar"><button className="quick-add income-add" onClick={()=>setKind('income')}><span>＋</span> Agregar ingreso</button><button className="quick-add expense-add" onClick={()=>setKind('expense')}><span>＋</span> Agregar gasto</button></div>
 {kind&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setKind(null)}><div className="modal-card"><div className="modal-title"><div><span className="eyebrow">REGISTRAR</span><h3>{kind==='income'?'Nuevo ingreso':'Nuevo gasto'}</h3></div><button type="button" className="modal-close" onClick={()=>setKind(null)}>×</button></div><SafeForm action={kind==='income'?addIncome:addExpense} className="modal-form" onSuccess={()=>setKind(null)} successMessage="Movimiento guardado"><input type="hidden" name="view_year" value={year}/><input type="hidden" name="view_month" value={month}/><label><span>Concepto</span><input name="concept" placeholder={kind==='income'?'Ej. Sueldo':'Ej. Supermercado'} required autoFocus/></label>{kind==='income'?<label><span>Origen</span><select name="source" required><option value="sueldo">Sueldo</option><option value="comision">Comisión</option><option value="bonus">Bonus</option><option value="extra">Extra</option></select></label>:<label><span>Categoría</span><select name="category" required>{categories.map(c=><option key={c.id}>{c.name}</option>)}</select></label>}<label><span>Monto</span><input name="amount" type="number" step=".01" min="0" placeholder="0" required/></label><label><span>Fecha</span><input name="occurred_on" type="date" defaultValue={fallbackDate} required/></label><label><span>Estado</span><select name="status" required><option value="pagado">Pagado</option><option value="pendiente">Pendiente</option></select></label><div className="modal-actions"><button type="button" className="secondary-btn" onClick={()=>setKind(null)}>Cancelar</button><button disabled={pending}>{pending?'Guardando…':kind==='income'?'Agregar ingreso':'Agregar gasto'}</button></div></SafeForm></div></div>}</>
}