BEGIN;
ALTER TABLE income ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE expense ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE recurring_items ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE recurring_items ADD COLUMN IF NOT EXISTS end_date DATE;
CREATE TABLE IF NOT EXISTS monthly_budgets(
  year INTEGER NOT NULL,
  month INTEGER NOT NULL CHECK(month BETWEEN 1 AND 12),
  amount NUMERIC(14,2) NOT NULL CHECK(amount>=0),
  PRIMARY KEY(year,month)
);
COMMIT;